-- ═══════════════════════════════════════════════════════════════════
-- Attendance backend + GPS geofencing
-- ═══════════════════════════════════════════════════════════════════
--
-- WHY THIS IS MORE THAN AN ALTER:
-- App clock-in / clock-out is stored in `public.attendance_sessions` (every
-- code path uses it: rpc('clock_in_attendance'|'clock_out_attendance') and
-- .from('attendance_sessions')). That table — and its two RPCs — were never
-- applied to this database (the original 20260609_attendance.sql migration
-- did not run; `staff_shifts` was created separately with a uuid id). So the
-- bare `alter table ... add column` failed with "relation does not exist".
--
-- This migration creates the table (with the GPS columns built in), its
-- indexes, self-service RLS, and the clock RPCs. It is idempotent: re-running
-- is safe, and it no-ops if the objects already exist.
--
-- SCHEMA NOTE: `schedule_id` is uuid here (references staff_shifts.id, which is
-- uuid in this database) — corrected from the bigint in 20260609_attendance.sql.

-- ── Table ──
create table if not exists public.attendance_sessions (
  id bigint generated by default as identity primary key,
  outlet_id uuid not null default '00000000-0000-0000-0000-000000000001'
    references public.outlets(id) on delete cascade,
  staff_user_id uuid not null references public.staff_profiles(id) on delete cascade,
  schedule_id uuid references public.staff_shifts(id) on delete set null,
  business_date date not null default current_date,
  clock_in timestamptz not null,
  clock_out timestamptz,
  clock_method text not null default 'app' check (clock_method in (
    'app', 'manager_manual', 'owner_correction'
  )),
  end_reason text check (end_reason in (
    'app', 'auto_closed', 'manager_manual', 'owner_correction'
  )),
  correction_note text,
  corrected_by uuid references public.staff_profiles(id),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ── GPS geofencing columns (the original intent of this migration) ──
alter table public.attendance_sessions
  add column if not exists clock_in_latitude   double precision,
  add column if not exists clock_in_longitude  double precision,
  add column if not exists clock_in_accuracy   double precision,
  add column if not exists clock_in_distance   double precision,
  add column if not exists clock_out_latitude  double precision,
  add column if not exists clock_out_longitude double precision,
  add column if not exists clock_out_accuracy  double precision,
  add column if not exists clock_out_distance  double precision;

-- ── Indexes ──
create index if not exists attendance_sessions_date_idx
  on public.attendance_sessions(business_date);
create index if not exists attendance_sessions_staff_date_idx
  on public.attendance_sessions(staff_user_id, business_date);
create index if not exists attendance_sessions_open_idx
  on public.attendance_sessions(staff_user_id)
  where clock_out is null;

-- ── RLS: self-service (an employee manages only their own 'app' sessions) ──
alter table public.attendance_sessions enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public'
    and tablename = 'attendance_sessions' and policyname = 'attendance_sessions_read_own') then
    create policy attendance_sessions_read_own on public.attendance_sessions
      for select to authenticated using (staff_user_id = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public'
    and tablename = 'attendance_sessions' and policyname = 'attendance_sessions_insert_own') then
    create policy attendance_sessions_insert_own on public.attendance_sessions
      for insert to authenticated
      with check (
        staff_user_id = auth.uid()
        and clock_method = 'app'
        and corrected_by is null
        and correction_note is null
      );
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public'
    and tablename = 'attendance_sessions' and policyname = 'attendance_sessions_update_own') then
    create policy attendance_sessions_update_own on public.attendance_sessions
      for update to authenticated
      using (staff_user_id = auth.uid() and clock_method = 'app')
      with check (staff_user_id = auth.uid() and clock_method = 'app');
  end if;

  -- Owner/manager read-all — only if the role helper exists in this database.
  if exists (select 1 from pg_proc where proname = 'staff_role_is')
     and not exists (select 1 from pg_policies where schemaname = 'public'
       and tablename = 'attendance_sessions' and policyname = 'attendance_sessions_read_all') then
    create policy attendance_sessions_read_all on public.attendance_sessions
      for select to authenticated
      using (public.staff_role_is(array['owner', 'manager']));
  end if;
end $$;

-- ── RPCs called by the app (security invoker → RLS above governs them) ──
create or replace function public.clock_in_attendance(
  _staff_user_id uuid,
  _business_date date
) returns public.attendance_sessions
language plpgsql security invoker as $$
declare _row public.attendance_sessions;
begin
  if exists (
    select 1 from public.attendance_sessions
    where staff_user_id = _staff_user_id and clock_out is null
  ) then
    raise exception 'Already clocked in';
  end if;

  insert into public.attendance_sessions
    (staff_user_id, business_date, clock_in, clock_method)
  values
    (_staff_user_id, coalesce(_business_date, current_date), now(), 'app')
  returning * into _row;

  return _row;
end $$;

create or replace function public.clock_out_attendance(
  _staff_user_id uuid
) returns public.attendance_sessions
language plpgsql security invoker as $$
declare _row public.attendance_sessions;
begin
  update public.attendance_sessions
     set clock_out = now(), end_reason = 'app', updated_at = now()
   where staff_user_id = _staff_user_id and clock_out is null
  returning * into _row;

  if _row.id is null then
    raise exception 'No open session to clock out';
  end if;

  return _row;
end $$;
