begin;

-- ═══════════════════════════════════════════════════════════════════
-- Purchase Module — Database Schema
-- Phase 1: purchase_requests, purchase_request_items
-- Kitchen/Front Desk submit requests without prices.
-- Manager/Owner approve and confirm prices.
-- ═══════════════════════════════════════════════════════════════════

-- ── Outlets (shared, if not exists) ──
create table if not exists public.outlets (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Wenxin Main',
  created_at timestamptz not null default now()
);

insert into public.outlets (id, name)
values ('00000000-0000-0000-0000-000000000001', 'Wenxin Main')
on conflict (id) do nothing;

-- ── Purchase Requests ──
create table if not exists public.purchase_requests (
  id bigint generated by default as identity primary key,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  business_date date not null default current_date,
  status text not null default 'draft' check (status in (
    'draft', 'submitted', 'approved', 'rejected', 'confirmed', 'purchased', 'cancelled'
  )),
  urgency text not null default 'normal' check (urgency in (
    'low', 'normal', 'high', 'urgent'
  )),
  requested_by uuid not null references public.staff_profiles(id),
  approved_by uuid references public.staff_profiles(id),
  approved_at timestamptz,
  confirmed_by uuid references public.staff_profiles(id),
  confirmed_at timestamptz,
  rejection_reason text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists purchase_requests_date_idx
  on public.purchase_requests(business_date, outlet_id);
create index if not exists purchase_requests_status_idx
  on public.purchase_requests(status, outlet_id);
create index if not exists purchase_requests_requested_by_idx
  on public.purchase_requests(requested_by, business_date);

-- ── Purchase Request Items ──
create table if not exists public.purchase_request_items (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.purchase_requests(id) on delete cascade,
  item_name text not null,
  quantity numeric(10,2) not null check (quantity > 0),
  unit text not null,
  reason text,
  urgency text not null default 'normal' check (urgency in (
    'low', 'normal', 'high', 'urgent'
  )),
  notes text,
  supplier_id bigint references public.suppliers(id) on delete set null,
  unit_price numeric(10,2),       -- nullable: set by Manager/Owner only
  total_price numeric(10,2),       -- nullable: computed or set by Manager/Owner
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists purchase_request_items_request_idx
  on public.purchase_request_items(request_id);

-- ═══════════════════════════════════════════════════════════════════
-- RLS Policies
-- ═══════════════════════════════════════════════════════════════════

alter table public.purchase_requests enable row level security;
alter table public.purchase_request_items enable row level security;

-- Purchase Requests: read
create policy purchase_requests_read_own on public.purchase_requests
  for select to authenticated
  using (
    requested_by = auth.uid()
    or public.staff_role_is(array['owner', 'manager'])
  );

-- Purchase Requests: insert (any staff can create draft)
create policy purchase_requests_insert on public.purchase_requests
  for insert to authenticated
  with check (
    requested_by = auth.uid()
    and status = 'draft'
  );

-- Purchase Requests: update own draft
create policy purchase_requests_update_own on public.purchase_requests
  for update to authenticated
  using (
    requested_by = auth.uid()
    and status in ('draft', 'rejected')
  )
  with check (
    requested_by = auth.uid()
  );

-- Purchase Requests: manager/owner manage
create policy purchase_requests_manage on public.purchase_requests
  for update to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- Purchase Request Items: read via parent request
create policy purchase_request_items_read on public.purchase_request_items
  for select to authenticated
  using (
    exists (
      select 1 from public.purchase_requests r
      where r.id = request_id
        and (
          r.requested_by = auth.uid()
          or public.staff_role_is(array['owner', 'manager'])
        )
    )
  );

-- Purchase Request Items: insert via parent request (staff can add items)
create policy purchase_request_items_insert on public.purchase_request_items
  for insert to authenticated
  with check (
    exists (
      select 1 from public.purchase_requests r
      where r.id = request_id
        and r.requested_by = auth.uid()
        and r.status = 'draft'
    )
    -- unit_price and total_price must be null (staff cannot set prices)
    and unit_price is null
    and total_price is null
  );

-- Purchase Request Items: update via parent request
create policy purchase_request_items_update_own on public.purchase_request_items
  for update to authenticated
  using (
    exists (
      select 1 from public.purchase_requests r
      where r.id = request_id
        and r.requested_by = auth.uid()
        and r.status in ('draft', 'rejected')
    )
  )
  with check (
    exists (
      select 1 from public.purchase_requests r
      where r.id = request_id
        and r.requested_by = auth.uid()
        and r.status in ('draft', 'rejected')
    )
    -- staff cannot set prices on update either
    and unit_price is null
    and total_price is null
  );

-- Purchase Request Items: manager/owner manage (can set prices)
create policy purchase_request_items_manage on public.purchase_request_items
  for update to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- ═══════════════════════════════════════════════════════════════════
-- Audit Triggers
-- ═══════════════════════════════════════════════════════════════════

create trigger write_operational_audit
  after insert or update or delete on public.purchase_requests
  for each row execute function public.write_operational_audit();

create trigger write_operational_audit
  after insert or update or delete on public.purchase_request_items
  for each row execute function public.write_operational_audit();

-- ═══════════════════════════════════════════════════════════════════
-- Schema Validation
-- ═══════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.purchase_requests') is null
    or to_regclass('public.purchase_request_items') is null then
    raise exception 'purchase schema is incomplete';
  end if;
end;
$$;

commit;
