-- ═══════════════════════════════════════════════════════════════════
-- Baseline Incidents and Tasks Tables
-- Originally created via Supabase dashboard. This migration ensures
-- they exist before later migrations add columns via ALTER TABLE.
-- Runs early in migration order (01_ prefix) so assets and checklist
-- column migrations can safely reference them.
-- ═══════════════════════════════════════════════════════════════════

-- ── Incidents ──
create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  title text not null,
  incident_type text not null default 'other',
  severity text not null default 'medium',
  status text not null default 'open',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ── Tasks ──
create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  date date not null default current_date,
  title text not null,
  task_type text not null default 'other',
  priority text not null default 'medium',
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
