begin;

create table if not exists public.receivables (
  id              bigint generated by default as identity primary key,
  customer_name   text not null,
  original_amount numeric(12,2) not null check (original_amount > 0),
  paid_amount     numeric(12,2) not null default 0 check (paid_amount >= 0),
  due_date        date,
  status          text not null default 'outstanding'
                    check (status in ('outstanding', 'partial', 'paid', 'overdue')),
  notes           text,
  created_by      uuid,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists public.payables (
  id              bigint generated by default as identity primary key,
  supplier_name   text not null,
  original_amount numeric(12,2) not null check (original_amount > 0),
  paid_amount     numeric(12,2) not null default 0 check (paid_amount >= 0),
  due_date        date,
  status          text not null default 'outstanding'
                    check (status in ('outstanding', 'partial', 'paid', 'overdue')),
  notes           text,
  created_by      uuid,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- RLS: require auth for all operations; server actions enforce role checks
alter table public.receivables enable row level security;
alter table public.payables enable row level security;

create policy receivables_all on public.receivables
  for all to authenticated using (true) with check (true);

create policy payables_all on public.payables
  for all to authenticated using (true) with check (true);

commit;
