begin;

-- Reservations / Bookings table.
-- Replaces the hardcoded mock data on the Home dashboard and Reservations page.

create table if not exists public.reservations (
  id            bigint generated by default as identity primary key,
  customer_name text not null,
  phone         text,
  date          date not null default current_date,
  time_start    time not null,
  time_end      time,
  pax           integer not null default 1 check (pax > 0),
  table_area    text,
  notes         text,
  status        text not null default 'confirmed'
                  check (status in ('confirmed', 'pending', 'cancelled', 'completed', 'no_show')),
  created_by    uuid references public.staff_profiles(id),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists reservations_date_idx on public.reservations(date);
create index if not exists reservations_status_idx on public.reservations(status);

-- RLS: authenticated staff can read; owner/manager/front_desk can write
alter table public.reservations enable row level security;

create policy reservations_read on public.reservations
  for select to authenticated
  using (true);

create policy reservations_insert on public.reservations
  for insert to authenticated
  with check (public.staff_role_is(array['owner', 'manager', 'front_desk']));

create policy reservations_update on public.reservations
  for update to authenticated
  using (public.staff_role_is(array['owner', 'manager', 'front_desk']))
  with check (public.staff_role_is(array['owner', 'manager', 'front_desk']));

create policy reservations_delete on public.reservations
  for delete to authenticated
  using (public.staff_role_is(array['owner', 'manager']));

-- Enable realtime so the list updates across devices
alter publication supabase_realtime add table public.reservations;

commit;
