begin;

-- ═══════════════════════════════════════════════════════════════════
-- Inventory Module — Database Schema
-- Phase 1: inventory_items, stock_levels, movements, adjustments
-- ═══════════════════════════════════════════════════════════════════

-- ── Outlets (shared, if not exists) ──
create table if not exists public.outlets (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Wenxin Main',
  created_at timestamptz not null default now()
);

insert into public.outlets (id, name)
values ('00000000-0000-0000-0000-000000000001', 'Wenxin Main')
on conflict (id) do nothing;

-- ── Inventory Items ──
create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  name text not null,
  category text not null default 'General',
  unit text not null,
  reorder_level numeric(10,2) not null default 0,
  status text not null default 'active' check (status in (
    'active', 'inactive', 'discontinued'
  )),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (outlet_id, name)
);

create index if not exists inventory_items_category_idx
  on public.inventory_items(category, outlet_id);
create index if not exists inventory_items_status_idx
  on public.inventory_items(status, outlet_id);

-- ── Stock Levels (current quantity per item) ──
create table if not exists public.inventory_stock_levels (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.inventory_items(id) on delete cascade,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  current_quantity numeric(10,2) not null default 0,
  last_updated_at timestamptz not null default now(),
  unique (item_id, outlet_id)
);

-- Plain index on (item_id, outlet_id, current_quantity) — supports low-stock
-- queries efficiently without a subquery in the predicate (not allowed by PG).
create index if not exists inventory_stock_levels_low_idx
  on public.inventory_stock_levels(item_id, outlet_id, current_quantity);

-- ── Inventory Movements ──
create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.inventory_items(id) on delete cascade,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  movement_type text not null check (movement_type in (
    'purchase_receive', 'manual_adjustment', 'stock_check',
    'waste', 'usage', 'transfer_in', 'transfer_out'
  )),
  quantity numeric(10,2) not null,
  previous_quantity numeric(10,2) not null,
  new_quantity numeric(10,2) not null,
  reference_type text,
  reference_id bigint,
  notes text,
  created_by uuid references public.staff_profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists inventory_movements_item_idx
  on public.inventory_movements(item_id, created_at desc);
create index if not exists inventory_movements_type_idx
  on public.inventory_movements(movement_type, outlet_id);

-- ── Inventory Adjustments (manual stock corrections) ──
create table if not exists public.inventory_adjustments (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.inventory_items(id) on delete cascade,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  previous_quantity numeric(10,2) not null,
  adjusted_quantity numeric(10,2) not null,
  reason text not null,
  created_by uuid not null references public.staff_profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists inventory_adjustments_item_idx
  on public.inventory_adjustments(item_id, created_at desc);

-- ═══════════════════════════════════════════════════════════════════
-- RLS Policies
-- ═══════════════════════════════════════════════════════════════════

alter table public.inventory_items enable row level security;
alter table public.inventory_stock_levels enable row level security;
alter table public.inventory_movements enable row level security;
alter table public.inventory_adjustments enable row level security;

-- Inventory Items: owner/manager/kitchen read; owner/manager write
create policy inventory_items_read on public.inventory_items
  for select to authenticated
  using (public.staff_role_is(array['owner', 'manager', 'kitchen']));

create policy inventory_items_manage on public.inventory_items
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- Stock Levels: same visibility as items
create policy inventory_stock_levels_read on public.inventory_stock_levels
  for select to authenticated
  using (public.staff_role_is(array['owner', 'manager', 'kitchen']));

create policy inventory_stock_levels_manage on public.inventory_stock_levels
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- Movements: read for owner/manager/kitchen; insert for all allowed
create policy inventory_movements_read on public.inventory_movements
  for select to authenticated
  using (public.staff_role_is(array['owner', 'manager', 'kitchen']));

create policy inventory_movements_insert on public.inventory_movements
  for insert to authenticated
  with check (public.staff_role_is(array['owner', 'manager', 'kitchen']));

-- Adjustments: owner/manager only
create policy inventory_adjustments_read on public.inventory_adjustments
  for select to authenticated
  using (public.staff_role_is(array['owner', 'manager']));

create policy inventory_adjustments_insert on public.inventory_adjustments
  for insert to authenticated
  with check (public.staff_role_is(array['owner', 'manager']));

-- ═══════════════════════════════════════════════════════════════════
-- Audit Triggers
-- ═══════════════════════════════════════════════════════════════════

create trigger write_operational_audit
  after insert or update or delete on public.inventory_items
  for each row execute function public.write_operational_audit();

create trigger write_operational_audit
  after insert or update on public.inventory_movements
  for each row execute function public.write_operational_audit();

create trigger write_operational_audit
  after insert or update on public.inventory_adjustments
  for each row execute function public.write_operational_audit();

-- ═══════════════════════════════════════════════════════════════════
-- Schema Validation
-- ═══════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.inventory_items') is null
    or to_regclass('public.inventory_stock_levels') is null
    or to_regclass('public.inventory_movements') is null
    or to_regclass('public.inventory_adjustments') is null then
    raise exception 'inventory schema is incomplete';
  end if;
end;
$$;

commit;
