begin;

-- ═══════════════════════════════════════════════════════════════════
-- Attendance Module — Database Schema
-- Phase 1: attendance_sessions, staff_shifts, restaurant_settings
-- Session-based model — multiple sessions per staff per day allowed.
-- ═══════════════════════════════════════════════════════════════════

-- ── Outlets (shared, if not exists) ──
create table if not exists public.outlets (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Wenxin Main',
  created_at timestamptz not null default now()
);

insert into public.outlets (id, name)
values ('00000000-0000-0000-0000-000000000001', 'Wenxin Main')
on conflict (id) do nothing;

-- ── Staff Shifts ──
-- Weekly shift assignments. One row per staff per date.
-- Shared between Schedule and Attendance modules.

create table if not exists public.staff_shifts (
  id bigint generated by default as identity primary key,
  staff_user_id uuid not null references public.staff_profiles(id) on delete cascade,
  date date not null,
  shift_type text not null check (shift_type in (
    'morning', 'full', 'afternoon', 'off', 'leave'
  )),
  shift_label text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (staff_user_id, date, shift_label)
);

create index if not exists staff_shifts_date_idx on public.staff_shifts(date);
create index if not exists staff_shifts_staff_date_idx on public.staff_shifts(staff_user_id, date);

-- ── Attendance Sessions ──
-- Clock in/out events. Multiple rows per staff per day are allowed.
-- Each row is one continuous work session.

create table if not exists public.attendance_sessions (
  id bigint generated by default as identity primary key,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  staff_user_id uuid not null references public.staff_profiles(id) on delete cascade,
  schedule_id bigint references public.staff_shifts(id) on delete set null,
  business_date date not null default current_date,
  clock_in timestamptz not null,
  clock_out timestamptz,
  clock_method text not null default 'app' check (clock_method in (
    'app', 'manager_manual', 'owner_correction'
  )),
  end_reason text check (end_reason in (
    'app', 'auto_closed', 'manager_manual', 'owner_correction'
  )),
  correction_note text,
  corrected_by uuid references public.staff_profiles(id),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists attendance_sessions_date_idx
  on public.attendance_sessions(business_date);
create index if not exists attendance_sessions_staff_date_idx
  on public.attendance_sessions(staff_user_id, business_date);
create index if not exists attendance_sessions_outlet_date_idx
  on public.attendance_sessions(outlet_id, business_date);
create index if not exists attendance_sessions_open_idx
  on public.attendance_sessions(staff_user_id)
  where clock_out is null;

-- ── Restaurant Settings ──
-- Key-value store for owner-configurable settings.

create table if not exists public.restaurant_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.staff_profiles(id)
);

insert into public.restaurant_settings (key, value)
values ('late_threshold_minutes', '15')
on conflict (key) do nothing;

-- ═══════════════════════════════════════════════════════════════════
-- RLS Policies
-- ═══════════════════════════════════════════════════════════════════

alter table public.staff_shifts enable row level security;
alter table public.attendance_sessions enable row level security;
alter table public.restaurant_settings enable row level security;

-- Staff Shifts
create policy staff_shifts_manage on public.staff_shifts
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

create policy staff_shifts_read_own on public.staff_shifts
  for select to authenticated
  using (staff_user_id = auth.uid());

-- Attendance Sessions — read
create policy attendance_sessions_read_all on public.attendance_sessions
  for select to authenticated
  using (public.staff_role_is(array['owner', 'manager']));

create policy attendance_sessions_read_own on public.attendance_sessions
  for select to authenticated
  using (staff_user_id = auth.uid());

-- Attendance Sessions — insert (self clock-in, app method only)
create policy attendance_sessions_insert_own on public.attendance_sessions
  for insert to authenticated
  with check (
    staff_user_id = auth.uid()
    and clock_method = 'app'
    and corrected_by is null
    and correction_note is null
  );

-- Attendance Sessions — update own (close own open session)
create policy attendance_sessions_update_own on public.attendance_sessions
  for update to authenticated
  using (
    staff_user_id = auth.uid()
    and clock_method = 'app'
  )
  with check (
    staff_user_id = auth.uid()
    and clock_method = 'app'
  );

-- Attendance Sessions — auto-close orphaned session
create policy attendance_sessions_auto_close on public.attendance_sessions
  for update to authenticated
  using (
    staff_user_id = auth.uid()
    and clock_out is null
  )
  with check (
    staff_user_id = auth.uid()
    and end_reason = 'auto_closed'
  );

-- Attendance Sessions — owner/manager corrections
create policy attendance_sessions_correct on public.attendance_sessions
  for update to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- Restaurant Settings — owner only
create policy restaurant_settings_owner on public.restaurant_settings
  for all to authenticated
  using (public.staff_role_is(array['owner']))
  with check (public.staff_role_is(array['owner']));

-- ═══════════════════════════════════════════════════════════════════
-- Audit Triggers
-- ═══════════════════════════════════════════════════════════════════

create trigger write_operational_audit
  after insert or update or delete on public.staff_shifts
  for each row execute function public.write_operational_audit();

create trigger write_operational_audit
  after insert or update or delete on public.attendance_sessions
  for each row execute function public.write_operational_audit();

-- ═══════════════════════════════════════════════════════════════════
-- Schema Validation
-- ═══════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.attendance_sessions') is null
    or to_regclass('public.staff_shifts') is null
    or to_regclass('public.restaurant_settings') is null then
    raise exception 'attendance schema is incomplete';
  end if;
end;
$$;

commit;
