begin;

-- Weekly Menu Composer — assemble meals from independent protein/vegetable/staple components.
-- Adds a new assignment table; does NOT replace bento_weekly_menu_items or bento_menu_library.

create table if not exists public.bento_weekly_menu_assignments (
  id            bigint generated by default as identity primary key,
  week_start    date not null,
  day_of_week   int not null check (day_of_week between 0 and 6),
  variant_id    bigint not null references public.bento_menu_variants(id) on delete cascade,
  protein_id    bigint references public.bento_proteins(id) on delete set null,
  vegetable_id  bigint references public.bento_vegetables(id) on delete set null,
  staple_id     bigint references public.bento_staples(id) on delete set null,
  notes         text,
  created_at    timestamptz not null default now(),
  unique (week_start, day_of_week, variant_id)
);

create index if not exists bento_weekly_menu_assignments_week_idx
  on public.bento_weekly_menu_assignments(week_start);

-- RLS
alter table public.bento_weekly_menu_assignments enable row level security;

create policy bento_weekly_menu_assignments_read on public.bento_weekly_menu_assignments
  for select to authenticated using (true);

create policy bento_weekly_menu_assignments_write on public.bento_weekly_menu_assignments
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

commit;
