-- Wave 1 / Migration #3 — bento_delivery_areas table + KK/JQ zone seed.
--
-- Source of truth: xin-bento-mobile/docs/DELIVERY_AREAS_SEED.md §3 (owner-confirmed
-- 2026-06-29), BACKEND_PLAN_V1.md §3a, MIGRATION_PLAN_V1.md §5.2.
-- Additive, idempotent, reversible.
--
-- Data-driven delivery zones + per-area single-order fee. V1 matching is simple
-- named areas only (match_type = 'area_name'); match_type is left extensible to
-- 'postcode' now and 'polygon' (PostGIS) later WITHOUT changing the order/pricing
-- contract -- resolve_delivery_area() (Wave 2) is the single seam.
--
-- Active/inactive: inactive rows (Zone 5) resolve as "outside service area". The
-- actual outside-area BLOCK is enforced by the order RPC in Wave 2 (#9); this
-- migration only supplies the data. Per-area fees here drive single-order pricing;
-- packages are always free in any supported area; single orders >= 5 meals free.
--
-- Dispatch origin: JQ Central / Jesselton Quay, KK. Fees rise with distance across
-- five zones: City Core RM4, Near Residential/School RM6, Extended KK RM8,
-- Conditional RM12 (active, gated at staff confirmation), Outside (inactive/blocked).
--
-- This migration DOES NOT touch deduction, triggers, balances, or pricing logic.
-- Apply manually in Supabase SQL Editor (staging first). Not applied by this draft.

begin;

create table if not exists public.bento_delivery_areas (
  id            bigint generated by default as identity primary key,
  area_name     text not null,
  match_type    text not null default 'area_name'
                  check (match_type in ('area_name', 'postcode')),
  match_value   text not null,
  delivery_fee  numeric(10, 2),           -- null for inactive/outside areas
  active        boolean not null default true,
  display_order integer not null default 0,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (match_type, match_value)
);

drop trigger if exists bento_delivery_areas_set_updated_at on public.bento_delivery_areas;
create trigger bento_delivery_areas_set_updated_at
before update on public.bento_delivery_areas
for each row execute function public.set_updated_at();

-- Seed the owner-confirmed zones (idempotent upsert keyed on match_type+match_value).
-- 29 rows total: 23 active (Zones 1-4) + 6 inactive (Zone 5).
insert into public.bento_delivery_areas
  (area_name, match_type, match_value, delivery_fee, active, display_order, notes)
values
  -- Zone 1 — KK City Core (RM 4)
  ('Jesselton Quay (JQ)', 'area_name', 'jesselton quay', 4, true, 10,  'Zone 1 KK City Core · dispatch origin'),
  ('JQ',                  'area_name', 'jq',             4, true, 15,  'Z1 City Core · alias for Jesselton Quay'),
  ('Suria Sabah',         'area_name', 'suria sabah',    4, true, 20,  'Zone 1 KK City Core'),
  ('Gaya Street',         'area_name', 'gaya street',    4, true, 30,  'Zone 1 KK City Core'),
  ('Api-Api',             'area_name', 'api-api',        4, true, 40,  'Zone 1 KK City Core'),
  ('Asia City',           'area_name', 'asia city',      4, true, 50,  'Zone 1 KK City Core'),
  ('Centre Point',        'area_name', 'centre point',   4, true, 60,  'Zone 1 KK City Core'),
  ('KK City Centre',      'area_name', 'kk city centre', 4, true, 70,  'Zone 1 KK City Core'),
  -- Zone 2 — Near Residential / School (RM 6)
  ('Likas',               'area_name', 'likas',          6, true, 80,  'Zone 2 Near Residential/School'),
  ('Damai',               'area_name', 'damai',          6, true, 90,  'Zone 2 Near Residential/School'),
  ('Luyang',              'area_name', 'luyang',         6, true, 100, 'Zone 2 Near Residential/School'),
  ('Foh Sang',            'area_name', 'foh sang',       6, true, 110, 'Zone 2 Near Residential/School'),
  ('Lintas',              'area_name', 'lintas',         6, true, 120, 'Zone 2 Near Residential/School'),
  ('Karamunsing',         'area_name', 'karamunsing',    6, true, 130, 'Zone 2 Near Residential/School'),
  -- Zone 3 — Extended KK (RM 8)
  ('Kolombong',           'area_name', 'kolombong',      8, true, 140, 'Zone 3 Extended KK'),
  ('Inanam',              'area_name', 'inanam',         8, true, 150, 'Zone 3 Extended KK'),
  ('Kepayan',             'area_name', 'kepayan',        8, true, 160, 'Zone 3 Extended KK'),
  ('Tanjung Aru',         'area_name', 'tanjung aru',    8, true, 170, 'Zone 3 Extended KK'),
  ('Sembulan',            'area_name', 'sembulan',       8, true, 180, 'Zone 3 Extended KK'),
  ('Sutera Harbour',      'area_name', 'sutera harbour', 8, true, 190, 'Zone 3 Extended KK'),
  -- Zone 4 — Conditional Area (RM 12, active; gated at staff confirmation)
  ('Penampang (near)',    'area_name', 'penampang',      12, true, 200, 'Zone 4 Conditional · route/5+ meals/corporate only'),
  ('Donggongon (near)',   'area_name', 'donggongon',     12, true, 210, 'Zone 4 Conditional · route/5+ meals/corporate only'),
  ('Menggatal',           'area_name', 'menggatal',      12, true, 220, 'Zone 4 Conditional · route/5+ meals/corporate only'),
  -- Zone 5 — Outside Area (inactive -> blocked; no fee)
  ('Putatan',             'area_name', 'putatan',        null, false, 230, 'Zone 5 Outside · not serviced'),
  ('Lok Kawi',            'area_name', 'lok kawi',       null, false, 240, 'Zone 5 Outside · not serviced'),
  ('Telipok',             'area_name', 'telipok',        null, false, 250, 'Zone 5 Outside · not serviced'),
  ('Tuaran',              'area_name', 'tuaran',         null, false, 260, 'Zone 5 Outside · not serviced'),
  ('Sepanggar (far)',     'area_name', 'sepanggar',      null, false, 270, 'Zone 5 Outside · not serviced'),
  ('Outstation / Other',  'area_name', 'outstation',     null, false, 280, 'Zone 5 Outside · catch term, not serviced')
on conflict (match_type, match_value) do update
set area_name     = excluded.area_name,
    delivery_fee  = excluded.delivery_fee,
    active        = excluded.active,
    display_order = excluded.display_order,
    notes         = excluded.notes,
    updated_at    = now();

-- RLS: lock down + STAFF management access. The customer-facing `authenticated`
-- read of ACTIVE rows is Wave 2 (MIGRATION_PLAN_V1.md #7) and is NOT added here.
alter table public.bento_delivery_areas enable row level security;
revoke all on table public.bento_delivery_areas from public, anon;
grant select, insert, update, delete on table public.bento_delivery_areas to authenticated;

drop policy if exists staff_bento_delivery_areas_select on public.bento_delivery_areas;
create policy staff_bento_delivery_areas_select on public.bento_delivery_areas
for select to authenticated
using (public.staff_role_is(array['owner', 'manager', 'kitchen', 'front_desk']));

drop policy if exists staff_bento_delivery_areas_write on public.bento_delivery_areas;
create policy staff_bento_delivery_areas_write on public.bento_delivery_areas
for all to authenticated
using (public.staff_role_is(array['owner', 'manager']))
with check (public.staff_role_is(array['owner', 'manager']));

commit;

-- Verification:
--   select count(*) filter (where active) as active_rows,
--          count(*) filter (where not active) as inactive_rows,
--          count(*) as total_rows
--   from public.bento_delivery_areas;
--   -- expect 23 active / 6 inactive / 29 total.
--
--   select area_name, delivery_fee, active from public.bento_delivery_areas
--   where match_value in ('likas', 'putatan', 'jq') order by display_order;
--   -- expect Likas=6/active, Putatan=null/inactive, JQ=4/active.
