begin;

-- ═══════════════════════════════════════════════════════════════════
-- Checklist Module — Database Schema
-- Phase 1: templates, runs, items, instances, item_responses
-- run_key support — one active instance per run per day.
-- ═══════════════════════════════════════════════════════════════════

-- ── Outlets (shared, if not exists) ──
create table if not exists public.outlets (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Wenxin Main',
  created_at timestamptz not null default now()
);

insert into public.outlets (id, name)
values ('00000000-0000-0000-0000-000000000001', 'Wenxin Main')
on conflict (id) do nothing;

-- ── Checklist Templates ──
create table if not exists public.checklist_templates (
  id bigint generated by default as identity primary key,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  name text not null,
  checklist_type text not null check (checklist_type in (
    'opening', 'closing', 'kitchen_hygiene', 'stock_check', 'cash_closing'
  )),
  description text not null default '',
  assigned_role text not null check (assigned_role in (
    'owner', 'manager', 'kitchen', 'front_desk'
  )),
  is_recurring boolean not null default true,
  requires_verification boolean not null default true,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (outlet_id, checklist_type)
);

create index if not exists checklist_templates_type_idx
  on public.checklist_templates(checklist_type);

-- ── Checklist Template Runs ──
create table if not exists public.checklist_template_runs (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.checklist_templates(id) on delete cascade,
  run_key text not null,
  scheduled_time time not null,
  created_at timestamptz not null default now(),
  unique (template_id, run_key)
);

create index if not exists checklist_template_runs_template_idx
  on public.checklist_template_runs(template_id);

-- ── Checklist Template Items ──
create table if not exists public.checklist_template_items (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.checklist_templates(id) on delete cascade,
  description text not null,
  category text not null default 'General',
  sort_order integer not null default 0,
  is_critical boolean not null default false,
  requires_note_on_fail boolean not null default true,
  inventory_ref text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists checklist_template_items_template_idx
  on public.checklist_template_items(template_id, sort_order);

-- ── Checklist Instances ──
create table if not exists public.checklist_instances (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.checklist_templates(id) on delete cascade,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  run_key text not null,
  business_date date not null,
  scheduled_time timestamptz not null,
  status text not null default 'pending' check (status in (
    'pending', 'in_progress', 'completed', 'verified'
  )),
  assigned_role text not null,
  completed_by uuid references public.staff_profiles(id),
  started_at timestamptz,
  completed_at timestamptz,
  verified_by uuid references public.staff_profiles(id),
  verified_at timestamptz,
  verification_note text,
  rejection_note text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists checklist_instances_date_idx
  on public.checklist_instances(business_date);
create index if not exists checklist_instances_status_idx
  on public.checklist_instances(status, business_date);
create index if not exists checklist_instances_template_date_idx
  on public.checklist_instances(template_id, business_date);
create unique index if not exists checklist_instances_one_active_per_run
  on public.checklist_instances(template_id, business_date, outlet_id, run_key)
  where status in ('pending', 'in_progress');

-- ── Checklist Item Responses ──
create table if not exists public.checklist_item_responses (
  id bigint generated by default as identity primary key,
  instance_id bigint not null references public.checklist_instances(id) on delete cascade,
  template_item_id bigint not null references public.checklist_template_items(id) on delete cascade,
  status text not null default 'pending' check (status in (
    'pending', 'pass', 'fail', 'skip'
  )),
  note text,
  responded_by uuid references public.staff_profiles(id),
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (instance_id, template_item_id)
);

create index if not exists checklist_item_responses_instance_idx
  on public.checklist_item_responses(instance_id);

-- ═══════════════════════════════════════════════════════════════════
-- Auto-Scheduling Function
-- ═══════════════════════════════════════════════════════════════════

create or replace function public.schedule_daily_checklists(target_date date)
returns setof public.checklist_instances
language plpgsql
security definer
set search_path = public
as $$
declare
  run_record record;
  instance public.checklist_instances;
  existing_count integer;
  scheduled_ts timestamptz;
begin
  for run_record in
    select
      r.id as run_id,
      r.run_key,
      r.scheduled_time,
      t.id as template_id,
      t.assigned_role
    from public.checklist_template_runs r
    join public.checklist_templates t on t.id = r.template_id
    where t.is_active and t.is_recurring
  loop
    select count(*) into existing_count
    from public.checklist_instances
    where template_id = run_record.template_id
      and business_date = target_date
      and run_key = run_record.run_key
      and status in ('pending', 'in_progress');

    if existing_count = 0 then
      scheduled_ts := target_date + run_record.scheduled_time;

      insert into public.checklist_instances (
        template_id, run_key, business_date, scheduled_time,
        assigned_role
      ) values (
        run_record.template_id, run_record.run_key, target_date, scheduled_ts,
        run_record.assigned_role
      )
      returning * into instance;

      insert into public.checklist_item_responses (
        instance_id, template_item_id, status
      )
      select instance.id, ti.id, 'pending'
      from public.checklist_template_items ti
      where ti.template_id = run_record.template_id
      order by ti.sort_order;

      return next instance;
    end if;
  end loop;
end;
$$;

-- ═══════════════════════════════════════════════════════════════════
-- Seed Templates, Runs, and Items
-- ═══════════════════════════════════════════════════════════════════

do $$
declare
  v_opening_id bigint;
  v_closing_id bigint;
  v_hygiene_id bigint;
  v_stock_id bigint;
  v_cash_id bigint;
begin
  -- Opening Checklist
  insert into public.checklist_templates (name, checklist_type, description, assigned_role, requires_verification, sort_order)
  values ('Opening Checklist', 'opening', 'Daily opening procedures', 'kitchen', true, 1)
  on conflict (outlet_id, checklist_type) do nothing
  returning id into v_opening_id;

  if v_opening_id is null then
    select id into v_opening_id from public.checklist_templates where checklist_type = 'opening';
  end if;

  insert into public.checklist_template_runs (template_id, run_key, scheduled_time)
  values (v_opening_id, 'opening', '08:00')
  on conflict (template_id, run_key) do nothing;

  insert into public.checklist_template_items (template_id, description, category, sort_order, is_critical)
  values
    (v_opening_id, 'All gas burners functioning', 'Equipment', 1, true),
    (v_opening_id, 'Rice cookers operational', 'Equipment', 2, true),
    (v_opening_id, 'Exhaust fans running', 'Equipment', 3, false),
    (v_opening_id, 'Kitchen surfaces sanitized', 'Hygiene', 4, true),
    (v_opening_id, 'Hand washing station stocked', 'Hygiene', 5, false),
    (v_opening_id, 'Cooking oil sufficient', 'Stock', 6, false),
    (v_opening_id, 'All menu ingredients available', 'Stock', 7, true),
    (v_opening_id, 'Fire extinguisher accessible', 'Safety', 8, true),
    (v_opening_id, 'First aid kit stocked', 'Safety', 9, false),
    (v_opening_id, 'Tables set and clean', 'Front', 10, false)
  on conflict do nothing;

  -- Closing Checklist
  insert into public.checklist_templates (name, checklist_type, description, assigned_role, requires_verification, sort_order)
  values ('Closing Checklist', 'closing', 'Daily closing procedures', 'kitchen', true, 2)
  on conflict (outlet_id, checklist_type) do nothing
  returning id into v_closing_id;

  if v_closing_id is null then
    select id into v_closing_id from public.checklist_templates where checklist_type = 'closing';
  end if;

  insert into public.checklist_template_runs (template_id, run_key, scheduled_time)
  values (v_closing_id, 'closing', '21:00')
  on conflict (template_id, run_key) do nothing;

  insert into public.checklist_template_items (template_id, description, category, sort_order, is_critical)
  values
    (v_closing_id, 'All gas burners turned off', 'Equipment', 1, true),
    (v_closing_id, 'All appliances switched off', 'Equipment', 2, true),
    (v_closing_id, 'Kitchen surfaces cleaned and sanitized', 'Hygiene', 3, true),
    (v_closing_id, 'Floors swept and mopped', 'Hygiene', 4, false),
    (v_closing_id, 'Trash removed and bins cleaned', 'Hygiene', 5, false),
    (v_closing_id, 'All food properly stored and covered', 'Stock', 6, true),
    (v_closing_id, 'Fridge and freezer doors sealed', 'Equipment', 7, true),
    (v_closing_id, 'Windows and doors locked', 'Safety', 8, true),
    (v_closing_id, 'Lights turned off (except security)', 'Safety', 9, false),
    (v_closing_id, 'Alarm system armed', 'Safety', 10, true)
  on conflict do nothing;

  -- Kitchen Hygiene
  insert into public.checklist_templates (name, checklist_type, description, assigned_role, requires_verification, sort_order)
  values ('Kitchen Hygiene', 'kitchen_hygiene', 'Kitchen hygiene inspection', 'kitchen', true, 3)
  on conflict (outlet_id, checklist_type) do nothing
  returning id into v_hygiene_id;

  if v_hygiene_id is null then
    select id into v_hygiene_id from public.checklist_templates where checklist_type = 'kitchen_hygiene';
  end if;

  insert into public.checklist_template_runs (template_id, run_key, scheduled_time)
  values
    (v_hygiene_id, 'morning', '10:00'),
    (v_hygiene_id, 'afternoon', '16:00')
  on conflict (template_id, run_key) do nothing;

  insert into public.checklist_template_items (template_id, description, category, sort_order, is_critical)
  values
    (v_hygiene_id, 'All food stored at correct temperature', 'Food Safety', 1, true),
    (v_hygiene_id, 'No cross-contamination risks observed', 'Food Safety', 2, true),
    (v_hygiene_id, 'Hand washing sinks stocked and accessible', 'Hygiene', 3, true),
    (v_hygiene_id, 'Food preparation surfaces sanitized', 'Hygiene', 4, true),
    (v_hygiene_id, 'Waste bins not overflowing', 'Hygiene', 5, false),
    (v_hygiene_id, 'Staff wearing clean uniforms and hair restraints', 'Staff', 6, false),
    (v_hygiene_id, 'No pests or pest evidence observed', 'Pest Control', 7, true),
    (v_hygiene_id, 'Cleaning chemicals properly stored and labeled', 'Safety', 8, true)
  on conflict do nothing;

  -- Stock Check
  insert into public.checklist_templates (name, checklist_type, description, assigned_role, requires_verification, sort_order)
  values ('Stock Check', 'stock_check', 'Daily stock level verification', 'kitchen', false, 4)
  on conflict (outlet_id, checklist_type) do nothing
  returning id into v_stock_id;

  if v_stock_id is null then
    select id into v_stock_id from public.checklist_templates where checklist_type = 'stock_check';
  end if;

  insert into public.checklist_template_runs (template_id, run_key, scheduled_time)
  values (v_stock_id, 'daily', '09:00')
  on conflict (template_id, run_key) do nothing;

  insert into public.checklist_template_items (template_id, description, category, sort_order, is_critical, inventory_ref)
  values
    (v_stock_id, 'Cooking oil stock sufficient', 'Condiments', 1, true, 'cooking_oil'),
    (v_stock_id, 'Soy sauce stock sufficient', 'Condiments', 2, false, 'soy_sauce'),
    (v_stock_id, 'Rice stock sufficient', 'Staples', 3, true, 'rice'),
    (v_stock_id, 'Chicken stock sufficient for today', 'Meat', 4, true, 'chicken'),
    (v_stock_id, 'Pork stock sufficient for today', 'Meat', 5, true, 'pork'),
    (v_stock_id, 'Vegetables fresh and sufficient', 'Vegetables', 6, true, 'vegetables'),
    (v_stock_id, 'Takeaway packaging stock sufficient', 'Supplies', 7, false, 'packaging'),
    (v_stock_id, 'Cleaning supplies stock sufficient', 'Supplies', 8, false, 'cleaning')
  on conflict do nothing;

  -- Cash Closing
  insert into public.checklist_templates (name, checklist_type, description, assigned_role, requires_verification, sort_order)
  values ('Cash Closing', 'cash_closing', 'End-of-day cash closing procedures', 'front_desk', true, 5)
  on conflict (outlet_id, checklist_type) do nothing
  returning id into v_cash_id;

  if v_cash_id is null then
    select id into v_cash_id from public.checklist_templates where checklist_type = 'cash_closing';
  end if;

  insert into public.checklist_template_runs (template_id, run_key, scheduled_time)
  values (v_cash_id, 'cash_closing', '21:00')
  on conflict (template_id, run_key) do nothing;

  insert into public.checklist_template_items (template_id, description, category, sort_order, is_critical)
  values
    (v_cash_id, 'Cash register total matches POS report', 'Reconciliation', 1, true),
    (v_cash_id, 'All card transactions batched and settled', 'Reconciliation', 2, true),
    (v_cash_id, 'E-wallet totals verified', 'Reconciliation', 3, true),
    (v_cash_id, 'Cash counted and verified by two staff', 'Cash', 4, true),
    (v_cash_id, 'Cash difference documented and explained', 'Cash', 5, true),
    (v_cash_id, 'Float prepared for next day', 'Cash', 6, false),
    (v_cash_id, 'Daily sales summary printed and signed', 'Reporting', 7, false),
    (v_cash_id, 'Cash securely stored in safe', 'Cash', 8, true)
  on conflict do nothing;
end;
$$;

-- ═══════════════════════════════════════════════════════════════════
-- RLS Policies
-- ═══════════════════════════════════════════════════════════════════

alter table public.checklist_templates enable row level security;
alter table public.checklist_template_runs enable row level security;
alter table public.checklist_template_items enable row level security;
alter table public.checklist_instances enable row level security;
alter table public.checklist_item_responses enable row level security;

-- Templates
create policy checklist_templates_read on public.checklist_templates
  for select to authenticated
  using (is_active or public.staff_role_is(array['owner', 'manager']));

create policy checklist_templates_manage on public.checklist_templates
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

create policy checklist_templates_delete on public.checklist_templates
  for delete to authenticated
  using (public.staff_role_is(array['owner']));

-- Template Runs — inherit from parent template
create policy checklist_template_runs_read on public.checklist_template_runs
  for select to authenticated
  using (
    exists (
      select 1 from public.checklist_templates t
      where t.id = template_id
        and (t.is_active or public.staff_role_is(array['owner', 'manager']))
    )
  );

-- Template Items
create policy checklist_template_items_read on public.checklist_template_items
  for select to authenticated
  using (
    exists (
      select 1 from public.checklist_templates t
      where t.id = template_id
        and (t.is_active or public.staff_role_is(array['owner', 'manager']))
    )
  );

create policy checklist_template_items_manage on public.checklist_template_items
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- Instances
create policy checklist_instances_read_all on public.checklist_instances
  for select to authenticated
  using (public.staff_role_is(array['owner', 'manager']));

create policy checklist_instances_read_role on public.checklist_instances
  for select to authenticated
  using (
    assigned_role = (
      select role from public.staff_profiles where id = auth.uid()
    )
  );

create policy checklist_instances_update_role on public.checklist_instances
  for update to authenticated
  using (
    assigned_role = (
      select role from public.staff_profiles where id = auth.uid()
    )
    and completed_by is null
  )
  with check (
    assigned_role = (
      select role from public.staff_profiles where id = auth.uid()
    )
  );

create policy checklist_instances_manage on public.checklist_instances
  for update to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

create policy checklist_instances_insert_system on public.checklist_instances
  for insert to authenticated
  with check (true);

-- Item Responses
create policy checklist_item_responses_read on public.checklist_item_responses
  for select to authenticated
  using (
    exists (
      select 1 from public.checklist_instances i
      where i.id = instance_id
        and (
          public.staff_role_is(array['owner', 'manager'])
          or i.assigned_role = (
            select role from public.staff_profiles where id = auth.uid()
          )
        )
    )
  );

create policy checklist_item_responses_respond on public.checklist_item_responses
  for all to authenticated
  using (
    exists (
      select 1 from public.checklist_instances i
      where i.id = instance_id
        and i.assigned_role = (
          select role from public.staff_profiles where id = auth.uid()
        )
        and i.completed_by is null
    )
  )
  with check (
    exists (
      select 1 from public.checklist_instances i
      where i.id = instance_id
        and i.assigned_role = (
          select role from public.staff_profiles where id = auth.uid()
        )
    )
  );

create policy checklist_item_responses_manage on public.checklist_item_responses
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- ═══════════════════════════════════════════════════════════════════
-- Audit Triggers
-- ═══════════════════════════════════════════════════════════════════

create trigger write_operational_audit
  after insert or update or delete on public.checklist_templates
  for each row execute function public.write_operational_audit();

create trigger write_operational_audit
  after insert or update or delete on public.checklist_template_items
  for each row execute function public.write_operational_audit();

create trigger write_operational_audit
  after insert or update or delete on public.checklist_instances
  for each row execute function public.write_operational_audit();

create trigger write_operational_audit
  after insert or update on public.checklist_item_responses
  for each row execute function public.write_operational_audit();

-- ═══════════════════════════════════════════════════════════════════
-- Schema Validation
-- ═══════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.checklist_templates') is null
    or to_regclass('public.checklist_template_runs') is null
    or to_regclass('public.checklist_template_items') is null
    or to_regclass('public.checklist_instances') is null
    or to_regclass('public.checklist_item_responses') is null then
    raise exception 'checklist schema is incomplete';
  end if;
end;
$$;

commit;
