-- ═══════════════════════════════════════════════════════════════════
-- Suppliers Module — Database Schema
-- Phase 1: suppliers, supplier_contacts
-- Runs BEFORE purchase migration (alphabetical: 'b' < 'p').
-- ═══════════════════════════════════════════════════════════════════

-- ── Outlets (shared, if not exists) ──
create table if not exists public.outlets (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Wenxin Main',
  created_at timestamptz not null default now()
);

insert into public.outlets (id, name)
values ('00000000-0000-0000-0000-000000000001', 'Wenxin Main')
on conflict (id) do nothing;

-- ── Suppliers ──
create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  company_name text not null,
  contact_person text,
  phone text,
  whatsapp text,
  email text,
  address text,
  payment_terms text check (payment_terms in (
    'cod', 'net_7', 'net_14', 'net_30', 'net_60'
  )),
  status text not null default 'active' check (status in (
    'active', 'inactive', 'suspended'
  )),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (outlet_id, company_name)
);

create index if not exists suppliers_status_idx on public.suppliers(status, outlet_id);
create index if not exists suppliers_name_idx on public.suppliers(company_name);

-- ── Supplier Contacts ──
create table if not exists public.supplier_contacts (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete cascade,
  name text not null,
  role text,
  phone text,
  email text,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists supplier_contacts_supplier_idx
  on public.supplier_contacts(supplier_id);
create unique index if not exists supplier_contacts_one_primary
  on public.supplier_contacts(supplier_id)
  where is_primary = true;

-- ═══════════════════════════════════════════════════════════════════
-- RLS Policies
-- ═══════════════════════════════════════════════════════════════════

alter table public.suppliers enable row level security;
alter table public.supplier_contacts enable row level security;

-- Suppliers: owner/manager/kitchen read; owner/manager write
create policy suppliers_read on public.suppliers
  for select to authenticated
  using (public.staff_role_is(array['owner', 'manager', 'kitchen']));

create policy suppliers_manage on public.suppliers
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- Contacts: inherit supplier visibility
create policy supplier_contacts_read on public.supplier_contacts
  for select to authenticated
  using (
    exists (
      select 1 from public.suppliers s
      where s.id = supplier_id
        and public.staff_role_is(array['owner', 'manager', 'kitchen'])
    )
  );

create policy supplier_contacts_manage on public.supplier_contacts
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- ═══════════════════════════════════════════════════════════════════
-- Audit Triggers
-- ═══════════════════════════════════════════════════════════════════

create trigger write_operational_audit
  after insert or update or delete on public.suppliers
  for each row execute function public.write_operational_audit();

create trigger write_operational_audit
  after insert or update or delete on public.supplier_contacts
  for each row execute function public.write_operational_audit();

-- ═══════════════════════════════════════════════════════════════════
-- Schema Validation
-- ═══════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.suppliers') is null
    or to_regclass('public.supplier_contacts') is null then
    raise exception 'suppliers schema is incomplete';
  end if;
end;
$$;
