begin;

create table if not exists public.staff_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  staff_id text not null unique check (staff_id ~ '^[a-z0-9][a-z0-9._-]{2,31}$'),
  display_name text not null,
  role text not null check (role in ('owner', 'manager', 'kitchen', 'front_desk')),
  active boolean not null default true,
  must_change_password boolean not null default true,
  password_change_required_at timestamptz not null default now(),
  sessions_invalidated_at timestamptz,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_login_at timestamptz
);

create table if not exists public.staff_sessions (
  id uuid primary key,
  staff_user_id uuid not null references public.staff_profiles(id) on delete cascade,
  staff_id text not null,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  expires_at timestamptz not null,
  ended_at timestamptz,
  end_reason text check (end_reason in ('logout', 'expired', 'forced', 'suspended')),
  device_summary text not null default ''
);

create index if not exists staff_sessions_staff_user_idx
  on public.staff_sessions(staff_user_id, started_at desc);

create index if not exists staff_sessions_active_idx
  on public.staff_sessions(expires_at)
  where ended_at is null;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_staff_id text,
  action text not null,
  entity_type text not null,
  entity_id text,
  summary text not null,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_actor_created_idx
  on public.audit_logs(actor_user_id, created_at desc);

create index if not exists audit_logs_entity_created_idx
  on public.audit_logs(entity_type, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists staff_profiles_set_updated_at on public.staff_profiles;
create trigger staff_profiles_set_updated_at
before update on public.staff_profiles
for each row execute function public.set_updated_at();

create or replace function public.current_session_id()
returns uuid
language sql
stable
security definer
set search_path = public, auth
as $$
  select case
    when coalesce(auth.jwt() ->> 'session_id', '') ~
      '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$'
    then (auth.jwt() ->> 'session_id')::uuid
    else null
  end;
$$;

create or replace function public.is_current_staff_session_valid()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.staff_profiles p
    join auth.sessions s
      on s.user_id = p.id
     and s.id = public.current_session_id()
    where p.id = auth.uid()
      and p.active
      and s.created_at + interval '12 hours' > now()
      and (
        p.sessions_invalidated_at is null
        or s.created_at > p.sessions_invalidated_at
      )
  );
$$;

create or replace function public.current_staff_role()
returns text
language sql
stable
security definer
set search_path = public, auth
as $$
  select p.role
  from public.staff_profiles p
  where p.id = auth.uid()
    and p.active
    and public.is_current_staff_session_valid()
  limit 1;
$$;

create or replace function public.staff_role_is(allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select coalesce(public.current_staff_role() = any(allowed_roles), false);
$$;

create or replace function public.get_login_staff_profile()
returns table (
  id uuid,
  staff_id text,
  display_name text,
  role text,
  active boolean,
  must_change_password boolean
)
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    p.id,
    p.staff_id,
    p.display_name,
    p.role,
    p.active,
    p.must_change_password
  from public.staff_profiles p
  where p.id = auth.uid()
  limit 1;
$$;

create or replace function public.write_auth_audit(
  audit_action text,
  audit_entity_type text,
  audit_entity_id text,
  audit_summary text,
  audit_before jsonb default null,
  audit_after jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  actor_id uuid := auth.uid();
  actor_staff text;
begin
  select staff_id into actor_staff
  from public.staff_profiles
  where id = actor_id;

  insert into public.audit_logs (
    actor_user_id,
    actor_staff_id,
    action,
    entity_type,
    entity_id,
    summary,
    before_data,
    after_data
  ) values (
    actor_id,
    actor_staff,
    left(audit_action, 80),
    left(audit_entity_type, 80),
    left(audit_entity_id, 160),
    left(audit_summary, 500),
    audit_before,
    audit_after
  );
end;
$$;

create or replace function public.start_staff_session(device_summary text default '')
returns public.staff_sessions
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  session_row auth.sessions%rowtype;
  profile_row public.staff_profiles%rowtype;
  result public.staff_sessions%rowtype;
begin
  select * into session_row
  from auth.sessions
  where id = public.current_session_id()
    and user_id = auth.uid();

  if session_row.id is null then
    raise exception 'Authentication session is unavailable';
  end if;

  select * into profile_row
  from public.staff_profiles
  where id = auth.uid();

  if profile_row.id is null or not profile_row.active then
    raise exception 'Staff account is unavailable';
  end if;

  insert into public.staff_sessions (
    id,
    staff_user_id,
    staff_id,
    started_at,
    last_seen_at,
    expires_at,
    device_summary
  ) values (
    session_row.id,
    profile_row.id,
    profile_row.staff_id,
    session_row.created_at,
    now(),
    session_row.created_at + interval '12 hours',
    left(coalesce(device_summary, ''), 240)
  )
  on conflict (id) do update
    set last_seen_at = now(),
        device_summary = excluded.device_summary
  returning * into result;

  update public.staff_profiles
  set last_login_at = now()
  where id = profile_row.id;

  perform public.write_auth_audit(
    'login',
    'staff_session',
    session_row.id::text,
    'Staff signed in'
  );

  return result;
end;
$$;

create or replace function public.touch_staff_session()
returns timestamptz
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  touched_at timestamptz;
begin
  if not public.is_current_staff_session_valid() then
    raise exception 'Staff session has ended';
  end if;

  update public.staff_sessions
  set last_seen_at = now()
  where id = public.current_session_id()
    and staff_user_id = auth.uid()
    and ended_at is null
    and last_seen_at < now() - interval '5 minutes'
  returning last_seen_at into touched_at;

  if touched_at is null then
    select last_seen_at into touched_at
    from public.staff_sessions
    where id = public.current_session_id()
      and staff_user_id = auth.uid();
  end if;

  return touched_at;
end;
$$;

create or replace function public.end_current_staff_session(reason text default 'logout')
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if reason not in ('logout', 'expired') then
    raise exception 'Invalid session end reason';
  end if;

  update public.staff_sessions
  set ended_at = coalesce(ended_at, now()),
      end_reason = coalesce(end_reason, reason)
  where id = public.current_session_id()
    and staff_user_id = auth.uid();

  perform public.write_auth_audit(
    reason,
    'staff_session',
    coalesce(public.current_session_id()::text, auth.uid()::text),
    case when reason = 'expired' then 'Staff session expired' else 'Staff signed out' end
  );
end;
$$;

create or replace function public.complete_first_password_change()
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  required_at timestamptz;
  auth_updated_at timestamptz;
begin
  select password_change_required_at into required_at
  from public.staff_profiles
  where id = auth.uid()
    and active;

  select updated_at into auth_updated_at
  from auth.users
  where id = auth.uid();

  if required_at is null or auth_updated_at is null or auth_updated_at <= required_at then
    raise exception 'Password has not been changed';
  end if;

  update public.staff_profiles
  set must_change_password = false
  where id = auth.uid();

  perform public.write_auth_audit(
    'password_changed',
    'staff_profile',
    auth.uid()::text,
    'Staff changed the required password'
  );
end;
$$;

create or replace function public.invalidate_staff_sessions(
  target_user uuid,
  reason text default 'forced'
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  target_staff_id text;
begin
  if not public.staff_role_is(array['owner']) then
    raise exception 'Owner access required';
  end if;
  if reason not in ('forced', 'suspended') then
    raise exception 'Invalid session invalidation reason';
  end if;

  select staff_id into target_staff_id
  from public.staff_profiles
  where id = target_user;

  update public.staff_profiles
  set sessions_invalidated_at = now()
  where id = target_user;

  update public.staff_sessions
  set ended_at = coalesce(ended_at, now()),
      end_reason = coalesce(end_reason, reason)
  where staff_user_id = target_user
    and ended_at is null;

  delete from auth.sessions
  where user_id = target_user;

  perform public.write_auth_audit(
    case when reason = 'suspended' then 'account_suspended' else 'force_logout' end,
    'staff_profile',
    target_user::text,
    case
      when reason = 'suspended' then 'Owner suspended ' || coalesce(target_staff_id, 'staff account')
      else 'Owner forced logout for ' || coalesce(target_staff_id, 'staff account')
    end
  );
end;
$$;

create or replace function public.set_bento_order_status(
  order_id bigint,
  next_status text
)
returns void
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.staff_role_is(array['owner', 'manager', 'kitchen']) then
    raise exception 'Bento fulfillment access required';
  end if;
  if next_status not in ('pending', 'completed') then
    raise exception 'Invalid fulfillment status';
  end if;

  update public.bento_orders
  set status = next_status
  where id = order_id;

  if not found then
    raise exception 'Bento order not found';
  end if;
end;
$$;

create or replace function public.write_operational_audit()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  old_data jsonb;
  new_data jsonb;
  entity_key text;
begin
  old_data := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  new_data := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  entity_key := coalesce(new_data ->> 'id', old_data ->> 'id');

  perform public.write_auth_audit(
    lower(tg_op),
    tg_table_name,
    entity_key,
    initcap(lower(tg_op)) || ' ' || replace(tg_table_name, '_', ' '),
    old_data,
    new_data
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

alter table public.staff_profiles enable row level security;
alter table public.staff_sessions enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists staff_profiles_select on public.staff_profiles;
create policy staff_profiles_select on public.staff_profiles
for select to authenticated
using (
  public.is_current_staff_session_valid()
  and (id = auth.uid() or public.staff_role_is(array['owner']))
);

drop policy if exists staff_profiles_owner_insert on public.staff_profiles;
create policy staff_profiles_owner_insert on public.staff_profiles
for insert to authenticated
with check (public.staff_role_is(array['owner']));

drop policy if exists staff_profiles_owner_update on public.staff_profiles;
create policy staff_profiles_owner_update on public.staff_profiles
for update to authenticated
using (public.staff_role_is(array['owner']))
with check (public.staff_role_is(array['owner']));

drop policy if exists staff_profiles_owner_delete on public.staff_profiles;
create policy staff_profiles_owner_delete on public.staff_profiles
for delete to authenticated
using (public.staff_role_is(array['owner']));

drop policy if exists staff_sessions_select on public.staff_sessions;
create policy staff_sessions_select on public.staff_sessions
for select to authenticated
using (
  public.is_current_staff_session_valid()
  and (staff_user_id = auth.uid() or public.staff_role_is(array['owner']))
);

drop policy if exists audit_logs_owner_select on public.audit_logs;
create policy audit_logs_owner_select on public.audit_logs
for select to authenticated
using (public.staff_role_is(array['owner']));

create or replace view public.staff_directory
with (security_barrier = true)
as
select id, staff_id, display_name, role, active, last_login_at
from public.staff_profiles
where public.staff_role_is(array['owner', 'manager']);

revoke all on public.staff_profiles from public, anon;
revoke all on public.staff_sessions from public, anon;
revoke all on public.audit_logs from public, anon;
revoke all on public.staff_directory from public, anon;

grant select on public.staff_profiles to authenticated;
grant select on public.staff_sessions to authenticated;
grant select on public.audit_logs to authenticated;
grant select on public.staff_directory to authenticated;

revoke all on function public.current_session_id() from public, anon;
revoke all on function public.is_current_staff_session_valid() from public, anon;
revoke all on function public.current_staff_role() from public, anon;
revoke all on function public.staff_role_is(text[]) from public, anon;
revoke all on function public.get_login_staff_profile() from public, anon;
revoke all on function public.write_auth_audit(text, text, text, text, jsonb, jsonb) from public, anon;
revoke all on function public.start_staff_session(text) from public, anon;
revoke all on function public.touch_staff_session() from public, anon;
revoke all on function public.end_current_staff_session(text) from public, anon;
revoke all on function public.complete_first_password_change() from public, anon;
revoke all on function public.invalidate_staff_sessions(uuid, text) from public, anon;
revoke all on function public.set_bento_order_status(bigint, text) from public, anon;

grant execute on function public.current_session_id() to authenticated;
grant execute on function public.is_current_staff_session_valid() to authenticated;
grant execute on function public.current_staff_role() to authenticated;
grant execute on function public.staff_role_is(text[]) to authenticated;
grant execute on function public.get_login_staff_profile() to authenticated;
grant execute on function public.start_staff_session(text) to authenticated;
grant execute on function public.touch_staff_session() to authenticated;
grant execute on function public.end_current_staff_session(text) to authenticated;
grant execute on function public.complete_first_password_change() to authenticated;
grant execute on function public.invalidate_staff_sessions(uuid, text) to authenticated;
grant execute on function public.set_bento_order_status(bigint, text) to authenticated;

do $$
declare
  table_name text;
  policy_name text;
begin
  foreach table_name in array array[
    'daily_stats',
    'bento_orders',
    'bento_weekly_menu',
    'bento_customers',
    'bento_subscription_days',
    'bento_holidays',
    'purchase_items',
    'tasks',
    'incidents'
  ]
  loop
    if to_regclass('public.' || table_name) is not null then
      for policy_name in
        select p.polname
        from pg_policy p
        where p.polrelid = to_regclass('public.' || table_name)
      loop
        execute format('drop policy if exists %I on public.%I', policy_name, table_name);
      end loop;
      execute format('alter table public.%I enable row level security', table_name);
      execute format('revoke all on table public.%I from public, anon', table_name);
      execute format('grant select, insert, update, delete on table public.%I to authenticated', table_name);
    end if;
  end loop;
end;
$$;

alter table public.bento_orders add column if not exists time_slot text;

do $$
begin
  if to_regclass('public.daily_stats') is not null then
    execute 'drop policy if exists staff_daily_stats_select on public.daily_stats';
    execute $policy$
      create policy staff_daily_stats_select on public.daily_stats
      for select to authenticated
      using (public.staff_role_is(array['owner', 'manager']))
    $policy$;
  end if;

  if to_regclass('public.bento_orders') is not null then
    execute 'drop policy if exists staff_bento_orders_select on public.bento_orders';
    execute 'drop policy if exists staff_bento_orders_insert on public.bento_orders';
    execute 'drop policy if exists staff_bento_orders_update on public.bento_orders';
    execute 'drop policy if exists staff_bento_orders_delete on public.bento_orders';
    execute $policy$
      create policy staff_bento_orders_select on public.bento_orders
      for select to authenticated
      using (public.staff_role_is(array['owner', 'manager', 'front_desk']))
    $policy$;
    execute $policy$
      create policy staff_bento_orders_insert on public.bento_orders
      for insert to authenticated
      with check (public.staff_role_is(array['owner', 'manager', 'front_desk']))
    $policy$;
    execute $policy$
      create policy staff_bento_orders_update on public.bento_orders
      for update to authenticated
      using (public.staff_role_is(array['owner', 'manager', 'front_desk']))
      with check (public.staff_role_is(array['owner', 'manager', 'front_desk']))
    $policy$;
    execute $policy$
      create policy staff_bento_orders_delete on public.bento_orders
      for delete to authenticated
      using (public.staff_role_is(array['owner', 'manager', 'front_desk']))
    $policy$;

    execute $view$
      create or replace view public.bento_kitchen_orders
      with (security_barrier = true)
      as
      select
        id,
        date,
        customer_name,
        address,
        area,
        menu_type,
        time_slot,
        items,
        note,
        quantity,
        status
      from public.bento_orders
      where public.staff_role_is(array['owner', 'manager', 'kitchen'])
    $view$;
    execute 'revoke all on public.bento_kitchen_orders from public, anon';
    execute 'grant select on public.bento_kitchen_orders to authenticated';
  end if;

  if to_regclass('public.bento_weekly_menu') is not null then
    execute 'drop policy if exists staff_bento_weekly_menu_select on public.bento_weekly_menu';
    execute 'drop policy if exists staff_bento_weekly_menu_write on public.bento_weekly_menu';
    execute $policy$
      create policy staff_bento_weekly_menu_select on public.bento_weekly_menu
      for select to authenticated
      using (public.staff_role_is(array['owner', 'manager', 'kitchen', 'front_desk']))
    $policy$;
    execute $policy$
      create policy staff_bento_weekly_menu_write on public.bento_weekly_menu
      for all to authenticated
      using (public.staff_role_is(array['owner', 'manager']))
      with check (public.staff_role_is(array['owner', 'manager']))
    $policy$;
  end if;

  if to_regclass('public.bento_customers') is not null then
    execute 'drop policy if exists staff_bento_customers_all on public.bento_customers';
    execute $policy$
      create policy staff_bento_customers_all on public.bento_customers
      for all to authenticated
      using (public.staff_role_is(array['owner', 'manager', 'front_desk']))
      with check (public.staff_role_is(array['owner', 'manager', 'front_desk']))
    $policy$;
  end if;

  if to_regclass('public.bento_subscription_days') is not null then
    execute 'drop policy if exists staff_bento_subscription_days_all on public.bento_subscription_days';
    execute $policy$
      create policy staff_bento_subscription_days_all on public.bento_subscription_days
      for all to authenticated
      using (public.staff_role_is(array['owner', 'manager', 'front_desk']))
      with check (public.staff_role_is(array['owner', 'manager', 'front_desk']))
    $policy$;
  end if;

  if to_regclass('public.bento_holidays') is not null then
    execute 'drop policy if exists staff_bento_holidays_select on public.bento_holidays';
    execute 'drop policy if exists staff_bento_holidays_write on public.bento_holidays';
    execute $policy$
      create policy staff_bento_holidays_select on public.bento_holidays
      for select to authenticated
      using (public.staff_role_is(array['owner', 'manager', 'kitchen', 'front_desk']))
    $policy$;
    execute $policy$
      create policy staff_bento_holidays_write on public.bento_holidays
      for all to authenticated
      using (public.staff_role_is(array['owner', 'manager']))
      with check (public.staff_role_is(array['owner', 'manager']))
    $policy$;
  end if;

  if to_regclass('public.purchase_items') is not null then
    execute 'drop policy if exists staff_purchase_items_all on public.purchase_items';
    execute $policy$
      create policy staff_purchase_items_all on public.purchase_items
      for all to authenticated
      using (public.staff_role_is(array['owner', 'manager', 'kitchen']))
      with check (public.staff_role_is(array['owner', 'manager', 'kitchen']))
    $policy$;
  end if;

  if to_regclass('public.tasks') is not null then
    execute 'drop policy if exists staff_tasks_all on public.tasks';
    execute $policy$
      create policy staff_tasks_all on public.tasks
      for all to authenticated
      using (public.staff_role_is(array['owner', 'manager', 'kitchen', 'front_desk']))
      with check (public.staff_role_is(array['owner', 'manager', 'kitchen', 'front_desk']))
    $policy$;
  end if;

  if to_regclass('public.incidents') is not null then
    execute 'drop policy if exists staff_incidents_all on public.incidents';
    execute $policy$
      create policy staff_incidents_all on public.incidents
      for all to authenticated
      using (public.staff_role_is(array['owner', 'manager', 'front_desk']))
      with check (public.staff_role_is(array['owner', 'manager', 'front_desk']))
    $policy$;
  end if;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'bento_orders',
    'bento_customers',
    'bento_subscription_days',
    'bento_weekly_menu',
    'purchase_items',
    'tasks',
    'incidents'
  ]
  loop
    if to_regclass('public.' || table_name) is not null then
      execute format('drop trigger if exists write_operational_audit on public.%I', table_name);
      execute format(
        'create trigger write_operational_audit after insert or update or delete on public.%I for each row execute function public.write_operational_audit()',
        table_name
      );
    end if;
  end loop;
end;
$$;

do $$
begin
  if to_regclass('public.staff_profiles') is null
    or to_regclass('public.staff_sessions') is null
    or to_regclass('public.audit_logs') is null then
    raise exception 'staff authentication schema is incomplete';
  end if;
end;
$$;

commit;
