create table if not exists public.bento_subscription_days (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.bento_customers(id) on delete cascade,
  date date not null,
  status text not null default 'scheduled' check (status in ('scheduled', 'skipped', 'completed')),
  meal_number integer,
  menu_type text not null default 'standard',
  time_slot text not null default 'lunch',
  note text not null default '',
  order_id bigint references public.bento_orders(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (customer_id, date)
);

create index if not exists bento_subscription_days_customer_date_idx
  on public.bento_subscription_days(customer_id, date);

create index if not exists bento_subscription_days_date_status_idx
  on public.bento_subscription_days(date, status);

create table if not exists public.bento_holidays (
  id bigint generated by default as identity primary key,
  date date not null unique,
  name text not null,
  note text not null default '',
  created_at timestamptz not null default now()
);
