begin;

-- ═══════════════════════════════════════════════════════════════════
-- Assets Module — Database Schema
-- Phase 1: assets table + incident/task linkage
-- ═══════════════════════════════════════════════════════════════════

-- ── Outlets (shared, if not exists) ──
create table if not exists public.outlets (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Wenxin Main',
  created_at timestamptz not null default now()
);

insert into public.outlets (id, name)
values ('00000000-0000-0000-0000-000000000001', 'Wenxin Main')
on conflict (id) do nothing;

-- ── Assets ──
create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  asset_code text not null,
  name text not null,
  category text not null check (category in (
    'pos', 'printer', 'kitchen_equipment', 'refrigeration',
    'networking', 'furniture', 'other'
  )),
  description text,
  serial_number text,
  location text,
  purchase_date date,
  purchase_price numeric(10,2),
  warranty_expiry date,
  status text not null default 'active' check (status in (
    'active', 'under_repair', 'retired', 'disposed'
  )),
  notes text,
  created_by uuid references public.staff_profiles(id),
  disposed_at timestamptz,
  disposed_by uuid references public.staff_profiles(id),
  disposal_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (outlet_id, asset_code),
  unique (outlet_id, name)
);

create index if not exists assets_status_idx on public.assets(status, outlet_id);
create index if not exists assets_category_idx on public.assets(category, outlet_id);
create index if not exists assets_warranty_idx on public.assets(warranty_expiry)
  where warranty_expiry is not null;

-- ── Incident Linkage ──
alter table public.incidents
  add column if not exists asset_id bigint
  references public.assets(id) on delete set null;

create index if not exists incidents_asset_idx
  on public.incidents(asset_id);

-- ── Task Linkage ──
alter table public.tasks
  add column if not exists asset_id bigint
  references public.assets(id) on delete set null;

create index if not exists tasks_asset_idx
  on public.tasks(asset_id);

-- ═══════════════════════════════════════════════════════════════════
-- RLS Policies
-- ═══════════════════════════════════════════════════════════════════

alter table public.assets enable row level security;

-- All authenticated can read
create policy assets_read on public.assets
  for select to authenticated
  using (true);

-- Owner and Manager can manage
create policy assets_manage on public.assets
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- ═══════════════════════════════════════════════════════════════════
-- Audit Trigger
-- ═══════════════════════════════════════════════════════════════════

create trigger write_operational_audit
  after insert or update or delete on public.assets
  for each row execute function public.write_operational_audit();

-- ═══════════════════════════════════════════════════════════════════
-- Schema Validation
-- ═══════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.assets') is null then
    raise exception 'assets schema is incomplete';
  end if;
end;
$$;

commit;
