begin;

-- ═══════════════════════════════════════════════════════════════════
-- Bento Component Libraries — independent protein / vegetable / staple
-- components that can be assembled into weekly meals.
-- Additive — does NOT replace bento_menu_library or weekly menu.
-- ═══════════════════════════════════════════════════════════════════

-- 1. Proteins (main dishes)
create table if not exists public.bento_proteins (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- 2. Vegetables (side dishes)
create table if not exists public.bento_vegetables (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- 3. Staples (rice, noodles, etc.)
create table if not exists public.bento_staples (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  is_active   boolean not null default true,
  is_rice     boolean not null default false,
  created_at  timestamptz not null default now()
);

-- Reuse existing bento_menu_variants (Light / Flavorful / Vegetarian)
-- Seed if not already present.
insert into public.bento_menu_variants (code, name, display_order)
values
  ('light',      'Light',       1),
  ('flavorful',  'Flavorful',   2),
  ('vegetarian', 'Vegetarian',  3)
on conflict (code) do nothing;

-- ── RLS ────────────────────────────────────────────────────────────
alter table public.bento_proteins enable row level security;
alter table public.bento_vegetables enable row level security;
alter table public.bento_staples enable row level security;

-- All authenticated can read
create policy bento_proteins_read on public.bento_proteins
  for select to authenticated using (true);
create policy bento_vegetables_read on public.bento_vegetables
  for select to authenticated using (true);
create policy bento_staples_read on public.bento_staples
  for select to authenticated using (true);

-- Owner/manager can write
create policy bento_proteins_write on public.bento_proteins
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));
create policy bento_vegetables_write on public.bento_vegetables
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));
create policy bento_staples_write on public.bento_staples
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

commit;
