begin;

-- ═══════════════════════════════════════════════════════════════════
-- Bento Menu Library — configurable multi-variant weekly menu system.
-- Replaces the single-column-per-day bento_weekly_menu table.
-- ═══════════════════════════════════════════════════════════════════

-- 1. Configurable menu variants (Light, Flavorful, Vegetarian, etc.)
create table if not exists public.bento_menu_variants (
  id            bigint generated by default as identity primary key,
  code          text not null unique,
  name          text not null,
  display_order int not null default 0,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now()
);

-- 2. Reusable menu library — dishes that can be assigned to weeks
create table if not exists public.bento_menu_library (
  id            bigint generated by default as identity primary key,
  variant_id    bigint not null references public.bento_menu_variants(id) on delete cascade,
  dish_name     text not null,
  description   text,
  created_at    timestamptz not null default now()
);

create index if not exists bento_menu_library_variant_idx
  on public.bento_menu_library(variant_id);

-- 3. Weekly menu assignments — one row per week + day + variant
create table if not exists public.bento_weekly_menu_items (
  id                bigint generated by default as identity primary key,
  week_start        date not null,
  day_of_week       int not null check (day_of_week between 0 and 6),
  variant_id        bigint not null references public.bento_menu_variants(id) on delete cascade,
  menu_library_id   bigint references public.bento_menu_library(id) on delete set null,
  custom_name       text,
  created_at        timestamptz not null default now(),
  unique (week_start, day_of_week, variant_id)
);

create index if not exists bento_weekly_menu_items_week_idx
  on public.bento_weekly_menu_items(week_start);

-- ── RLS ────────────────────────────────────────────────────────────
alter table public.bento_menu_variants enable row level security;
alter table public.bento_menu_library enable row level security;
alter table public.bento_weekly_menu_items enable row level security;

-- All authenticated can read
create policy bento_menu_variants_read on public.bento_menu_variants
  for select to authenticated using (true);

create policy bento_menu_library_read on public.bento_menu_library
  for select to authenticated using (true);

create policy bento_weekly_menu_items_read on public.bento_weekly_menu_items
  for select to authenticated using (true);

-- Owner/manager can write
create policy bento_menu_variants_write on public.bento_menu_variants
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

create policy bento_menu_library_write on public.bento_menu_library
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

create policy bento_weekly_menu_items_write on public.bento_weekly_menu_items
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- ── Seed default variants ──────────────────────────────────────────
insert into public.bento_menu_variants (code, name, display_order)
values
  ('light',      'Light',       1),
  ('flavorful',  'Flavorful',   2),
  ('vegetarian', 'Vegetarian',  3)
on conflict (code) do nothing;

-- ── Seed sample menu library entries ────────────────────────────────
with light_id as (
  select id from public.bento_menu_variants where code = 'light'
), flavorful_id as (
  select id from public.bento_menu_variants where code = 'flavorful'
)
insert into public.bento_menu_library (variant_id, dish_name)
select id, dish
from (
  select (select id from light_id) as id, unnest(array[
    'Sliced Chicken with Cucumber & Black Fungus',
    'Stir-fried Diced Chicken with Tofu',
    'Shrimp with Silky Scrambled Egg'
  ]) as dish
  union all
  select (select id from flavorful_id) as id, unnest(array[
    'Potato Chicken & Beef Brisket',
    'Spicy Stir-fried Chicken',
    'Japanese Teriyaki Chicken'
  ]) as dish
) t
where id is not null;

commit;
