-- Migration: Staff Scheduling — fixed weekly off day, leave requests,
--            public holidays + paid-leave work invitations.
-- ─────────────────────────────────────────────────────────────────────────────
-- Adds three capabilities to the Staff → Schedule module:
--   1. fixed_off_weekday on staff_profiles (owner-set recurring weekly off day)
--   2. staff_leave_requests (staff submit → owner/manager approve/reject)
--   3. public_holidays (paid leave by default) + public_holiday_work_invitations
--      (owner/manager invite specific staff to work on a holiday)
--
-- Plus public.team_on_duty(date): a SECURITY DEFINER helper that returns who is
-- scheduled to work on a given date, so normal staff can see "Today's Team On
-- Duty" WITHOUT being granted RLS read access to everyone's leave/schedule rows.
--
-- Re-runnable: guarded with IF NOT EXISTS / DROP POLICY IF EXISTS.
-- Targets the LIVE schema: staff_shifts uses (staff_id, shift_date, shift_type).
-- ─────────────────────────────────────────────────────────────────────────────

begin;

-- ── 1. Fixed weekly off day ──────────────────────────────────────────────────
-- Postgres dow convention: 0 = Sunday … 6 = Saturday. NULL = no fixed off day.
alter table public.staff_profiles
  add column if not exists fixed_off_weekday smallint
  check (fixed_off_weekday between 0 and 6);

-- ── 2. Leave requests ────────────────────────────────────────────────────────
create table if not exists public.staff_leave_requests (
  id          bigint generated by default as identity primary key,
  staff_id    uuid not null references public.staff_profiles(id) on delete cascade,
  start_date  date not null,
  end_date    date not null,
  reason      text not null default '',
  notes       text,
  status      text not null default 'pending'
              check (status in ('pending', 'approved', 'rejected', 'cancelled')),
  reviewed_by uuid references public.staff_profiles(id),
  reviewed_at timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  check (end_date >= start_date)
);

create index if not exists staff_leave_requests_staff_status_idx
  on public.staff_leave_requests(staff_id, status);
create index if not exists staff_leave_requests_range_idx
  on public.staff_leave_requests(start_date, end_date);

alter table public.staff_leave_requests enable row level security;

-- Staff: read / create / cancel their own. Owner+manager: full manage.
drop policy if exists staff_leave_requests_read_own  on public.staff_leave_requests;
create policy staff_leave_requests_read_own on public.staff_leave_requests
  for select to authenticated
  using (staff_id = auth.uid());

drop policy if exists staff_leave_requests_manage_all on public.staff_leave_requests;
create policy staff_leave_requests_manage_all on public.staff_leave_requests
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

drop policy if exists staff_leave_requests_insert_own on public.staff_leave_requests;
create policy staff_leave_requests_insert_own on public.staff_leave_requests
  for insert to authenticated
  with check (staff_id = auth.uid() and status = 'pending');

-- Staff may only flip their own still-pending request to 'cancelled'.
drop policy if exists staff_leave_requests_cancel_own on public.staff_leave_requests;
create policy staff_leave_requests_cancel_own on public.staff_leave_requests
  for update to authenticated
  using (staff_id = auth.uid() and status = 'pending')
  with check (staff_id = auth.uid() and status = 'cancelled');

-- ── 3a. Public holidays ──────────────────────────────────────────────────────
create table if not exists public.public_holidays (
  id           bigint generated by default as identity primary key,
  holiday_date date not null unique,
  name         text not null,
  is_paid      boolean not null default true,
  created_at   timestamptz not null default now()
);

alter table public.public_holidays enable row level security;

drop policy if exists public_holidays_read_all on public.public_holidays;
create policy public_holidays_read_all on public.public_holidays
  for select to authenticated
  using (true);

drop policy if exists public_holidays_manage on public.public_holidays;
create policy public_holidays_manage on public.public_holidays
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- Seed Sabah / Malaysia 2026 public holidays. Islamic- and lunar-calendar dates
-- are best estimates — owner can correct them via the holiday management screen.
insert into public.public_holidays (holiday_date, name)
values
  ('2026-01-01', 'New Year''s Day'),
  ('2026-02-17', 'Chinese New Year'),
  ('2026-02-18', 'Chinese New Year (Second Day)'),
  ('2026-03-20', 'Hari Raya Aidilfitri (est.)'),
  ('2026-03-21', 'Hari Raya Aidilfitri Second Day (est.)'),
  ('2026-05-01', 'Labour Day'),
  ('2026-05-27', 'Hari Raya Haji (est.)'),
  ('2026-05-30', 'Pesta Kaamatan'),
  ('2026-05-31', 'Pesta Kaamatan (Second Day) / Wesak Day'),
  ('2026-06-01', 'Agong''s Birthday'),
  ('2026-06-16', 'Awal Muharram (est.)'),
  ('2026-08-25', 'Maulidur Rasul (est.)'),
  ('2026-08-31', 'National Day (Merdeka)'),
  ('2026-09-16', 'Malaysia Day'),
  ('2026-10-03', 'Sabah Governor''s Birthday'),
  ('2026-11-08', 'Deepavali (est.)'),
  ('2026-12-25', 'Christmas Day')
on conflict (holiday_date) do nothing;

-- ── 3b. Public holiday work invitations ──────────────────────────────────────
-- One row = this staff member is invited / eligible to work that public holiday.
create table if not exists public.public_holiday_work_invitations (
  id           bigint generated by default as identity primary key,
  holiday_date date not null,
  staff_id     uuid not null references public.staff_profiles(id) on delete cascade,
  invited_by   uuid references public.staff_profiles(id),
  created_at   timestamptz not null default now(),
  unique (holiday_date, staff_id)
);

create index if not exists holiday_invitations_date_idx
  on public.public_holiday_work_invitations(holiday_date);

alter table public.public_holiday_work_invitations enable row level security;

drop policy if exists holiday_invitations_read_own on public.public_holiday_work_invitations;
create policy holiday_invitations_read_own on public.public_holiday_work_invitations
  for select to authenticated
  using (staff_id = auth.uid());

drop policy if exists holiday_invitations_manage on public.public_holiday_work_invitations;
create policy holiday_invitations_manage on public.public_holiday_work_invitations
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- ── 4. team_on_duty(date) — privacy-safe "who is working" lookup ─────────────
-- SECURITY DEFINER: reads everyone's leave / shift / holiday data internally but
-- only returns the names + roles of staff resolved to "working" that date.
-- Mirrors the TS priority engine in lib/schedule/resolveScheduleStatus.ts —
-- keep the two in sync. Priority (highest → lowest):
--   approved leave → off · holiday+invited → work · holiday → off ·
--   manual shift override → its type · fixed weekly off → off · else → work.
create or replace function public.team_on_duty(target_date date)
returns table (staff_id uuid, display_name text, role text)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.display_name, p.role
  from public.staff_profiles p
  where p.active = true
    and coalesce(p.archived, false) = false
    and p.role <> 'owner'
    and case
      when exists (
        select 1 from public.staff_leave_requests lr
        where lr.staff_id = p.id
          and lr.status = 'approved'
          and target_date between lr.start_date and lr.end_date
      ) then false
      when exists (
        select 1 from public.public_holidays h where h.holiday_date = target_date
      ) then exists (
        select 1 from public.public_holiday_work_invitations inv
        where inv.holiday_date = target_date and inv.staff_id = p.id
      )
      when exists (
        select 1 from public.staff_shifts s
        where s.staff_id = p.id and s.shift_date = target_date
      ) then (
        select s.shift_type not in ('off', 'leave')
        from public.staff_shifts s
        where s.staff_id = p.id and s.shift_date = target_date
        limit 1
      )
      when p.fixed_off_weekday = extract(dow from target_date)::int then false
      else true
    end
  order by p.display_name;
$$;

grant execute on function public.team_on_duty(date) to authenticated;

-- ── 5. Audit triggers (match existing operational-audit pattern) ─────────────
drop trigger if exists write_operational_audit on public.staff_leave_requests;
create trigger write_operational_audit
  after insert or update or delete on public.staff_leave_requests
  for each row execute function public.write_operational_audit();

drop trigger if exists write_operational_audit on public.public_holiday_work_invitations;
create trigger write_operational_audit
  after insert or update or delete on public.public_holiday_work_invitations
  for each row execute function public.write_operational_audit();

-- ── Validation ───────────────────────────────────────────────────────────────
do $$
begin
  if to_regclass('public.staff_leave_requests') is null
    or to_regclass('public.public_holidays') is null
    or to_regclass('public.public_holiday_work_invitations') is null then
    raise exception 'staff scheduling schema is incomplete';
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'staff_profiles'
      and column_name = 'fixed_off_weekday'
  ) then
    raise exception 'fixed_off_weekday column missing on staff_profiles';
  end if;
end;
$$;

commit;
