-- ═══════════════════════════════════════════════════════════════
-- Cashier Transactions — Phase 4
-- Sales amount source for Purchase-to-Sales Ratio KPI.
-- ═══════════════════════════════════════════════════════════════

create table if not exists public.cashier_transactions (
  id bigint generated by default as identity primary key,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  shift_id bigint not null references public.cashier_shifts(id) on delete cascade,
  business_date date not null default current_date,
  payment_method text not null check (payment_method in (
    'cash', 'touch_n_go', 'alipay', 'card', 'other'
  )),
  amount numeric(10,2) not null check (amount > 0),
  transaction_count integer not null default 1 check (transaction_count >= 0),
  source text not null default 'manual' check (source in ('manual', 'pos')),
  created_by uuid references public.staff_profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cashier_transactions_shift_idx
  on public.cashier_transactions(shift_id);
create index if not exists cashier_transactions_date_idx
  on public.cashier_transactions(business_date, outlet_id);

-- ═══════════════════════════════════════════════════════════════
-- RLS
-- ═══════════════════════════════════════════════════════════════

alter table public.cashier_transactions enable row level security;

create policy cashier_transactions_read on public.cashier_transactions
  for select to authenticated
  using (public.staff_role_is(array['owner', 'manager', 'front_desk']));

create policy cashier_transactions_insert on public.cashier_transactions
  for insert to authenticated
  with check (
    public.staff_role_is(array['owner', 'manager', 'front_desk'])
    and source = 'manual'
  );

-- ═══════════════════════════════════════════════════════════════
-- Audit Trigger
-- ═══════════════════════════════════════════════════════════════

create trigger write_operational_audit
  after insert or update or delete on public.cashier_transactions
  for each row execute function public.write_operational_audit();
