begin;

-- ═══════════════════════════════════════════════════════════════════
-- Cashier Module — Database Schema
-- Phase 2: cashier_shifts, payment_methods, cashier_adjustments
-- ═══════════════════════════════════════════════════════════════════

-- ── Outlets (shared) ──
create table if not exists public.outlets (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Wenxin Main',
  created_at timestamptz not null default now()
);

-- Seed default outlet if not exists
insert into public.outlets (id, name)
values ('00000000-0000-0000-0000-000000000001', 'Wenxin Main')
on conflict (id) do nothing;

-- ── Payment Methods ──
create table if not exists public.payment_methods (
  id bigint generated by default as identity primary key,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  name text not null,
  type text not null check (type in ('cash', 'card', 'ewallet', 'transfer', 'other')),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (outlet_id, name)
);

create index if not exists payment_methods_active_idx
  on public.payment_methods(outlet_id, sort_order)
  where is_active = true;

-- Seed default payment methods
insert into public.payment_methods (name, type, sort_order)
values
  ('Cash',        'cash',      1),
  ('Credit Card', 'card',      2),
  ('Debit Card',  'card',      3),
  ('Touch ''n Go','ewallet',   4),
  ('GrabPay',     'ewallet',   5),
  ('Bank Transfer','transfer', 6),
  ('Other',       'other',    99)
on conflict (outlet_id, name) do nothing;

-- ── Cashier Shifts ──
create table if not exists public.cashier_shifts (
  id bigint generated by default as identity primary key,
  outlet_id uuid not null references public.outlets(id) on delete cascade
    default '00000000-0000-0000-0000-000000000001',
  staff_user_id uuid not null references public.staff_profiles(id) on delete cascade,
  business_date date not null default current_date,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  status text not null default 'open' check (status in ('open', 'closing', 'closed', 'verified')),
  opening_balance numeric(10,2) not null default 0,
  expected_cash_total numeric(10,2) not null default 0,
  actual_cash_count numeric(10,2),
  cash_difference numeric(10,2) generated always as (
    coalesce(actual_cash_count, 0) - expected_cash_total
  ) stored,
  notes text,
  closed_by_staff_user_id uuid references public.staff_profiles(id),
  verified_by_staff_user_id uuid references public.staff_profiles(id),
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cashier_shifts_date_idx
  on public.cashier_shifts(business_date, outlet_id);
create index if not exists cashier_shifts_status_idx
  on public.cashier_shifts(status, outlet_id);
create unique index if not exists cashier_shifts_one_open_per_outlet
  on public.cashier_shifts(outlet_id)
  where status = 'open';

-- ── Cashier Adjustments ──
create table if not exists public.cashier_adjustments (
  id bigint generated by default as identity primary key,
  shift_id bigint not null references public.cashier_shifts(id) on delete cascade,
  type text not null check (type in ('pay_in', 'pay_out', 'correction')),
  amount numeric(10,2) not null check (amount > 0),
  reason text not null,
  authorized_by_staff_user_id uuid not null references public.staff_profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists cashier_adjustments_shift_idx
  on public.cashier_adjustments(shift_id);

-- ═══════════════════════════════════════════════════════════════════
-- RLS Policies
-- ═══════════════════════════════════════════════════════════════════

alter table public.payment_methods enable row level security;
alter table public.cashier_shifts enable row level security;
alter table public.cashier_adjustments enable row level security;

-- Payment Methods: all authenticated can read; owner/manager can manage
create policy payment_methods_read on public.payment_methods
  for select to authenticated
  using (public.staff_role_is(array['owner', 'manager', 'front_desk']));

create policy payment_methods_manage on public.payment_methods
  for all to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- Cashier Shifts: owner/manager read all; front_desk read own; kitchen no access
create policy cashier_shifts_read_all on public.cashier_shifts
  for select to authenticated
  using (public.staff_role_is(array['owner', 'manager']));

create policy cashier_shifts_read_own on public.cashier_shifts
  for select to authenticated
  using (
    staff_user_id = auth.uid()
    and public.staff_role_is(array['front_desk'])
  );

create policy cashier_shifts_insert on public.cashier_shifts
  for insert to authenticated
  with check (
    staff_user_id = auth.uid()
    and public.staff_role_is(array['owner', 'manager', 'front_desk'])
  );

create policy cashier_shifts_update_own on public.cashier_shifts
  for update to authenticated
  using (
    staff_user_id = auth.uid()
    and public.staff_role_is(array['owner', 'manager', 'front_desk'])
  )
  with check (
    staff_user_id = auth.uid()
    and public.staff_role_is(array['owner', 'manager', 'front_desk'])
  );

create policy cashier_shifts_manage on public.cashier_shifts
  for update to authenticated
  using (public.staff_role_is(array['owner', 'manager']))
  with check (public.staff_role_is(array['owner', 'manager']));

-- Cashier Adjustments: owner/manager full access; front_desk insert own shift
create policy cashier_adjustments_read on public.cashier_adjustments
  for select to authenticated
  using (
    exists (
      select 1 from public.cashier_shifts s
      where s.id = shift_id
        and (
          public.staff_role_is(array['owner', 'manager'])
          or (s.staff_user_id = auth.uid() and public.staff_role_is(array['front_desk']))
        )
    )
  );

create policy cashier_adjustments_insert on public.cashier_adjustments
  for insert to authenticated
  with check (
    public.staff_role_is(array['owner', 'manager', 'front_desk'])
    and exists (
      select 1 from public.cashier_shifts s
      where s.id = shift_id and s.status = 'open'
    )
  );

-- ═══════════════════════════════════════════════════════════════════
-- Audit Triggers
-- ═══════════════════════════════════════════════════════════════════

create trigger write_operational_audit
  after insert or update or delete on public.cashier_shifts
  for each row execute function public.write_operational_audit();

create trigger write_operational_audit
  after insert or update or delete on public.cashier_adjustments
  for each row execute function public.write_operational_audit();

-- ═══════════════════════════════════════════════════════════════════
-- Schema Validation
-- ═══════════════════════════════════════════════════════════════════

do $$
begin
  if to_regclass('public.cashier_shifts') is null
    or to_regclass('public.payment_methods') is null
    or to_regclass('public.cashier_adjustments') is null then
    raise exception 'cashier schema is incomplete';
  end if;
end;
$$;

commit;
