// ── Role-Permission Mappings ──
// Each role maps to the set of permissions it holds.
// This is the single source of truth for "who can do what."
// Phase 0: defined but not yet imported anywhere. Activated in Phase 0.5.

import { PERMISSION, type PermissionKey } from './permissionKeys'
import type { StaffRole } from './types'

type RolePermissions = Record<StaffRole, PermissionKey[]>

export const ROLE_PERMISSIONS: RolePermissions = {
  owner: [
    // Owner has all permissions
    ...Object.values(PERMISSION),
  ],

  manager: [
    // Home
    PERMISSION.VIEW_HOME,
    PERMISSION.VIEW_HOME_REVENUE,
    PERMISSION.VIEW_HOME_ALERTS,

    // Bento — full access
    PERMISSION.VIEW_BENTO,
    PERMISSION.VIEW_BENTO_ORDERS,
    PERMISSION.EDIT_BENTO_ORDERS,
    PERMISSION.VIEW_BENTO_CUSTOMERS,
    PERMISSION.EDIT_BENTO_CUSTOMERS,
    PERMISSION.VIEW_BENTO_PAYMENTS,
    PERMISSION.EDIT_BENTO_PAYMENTS,
    PERMISSION.VIEW_BENTO_PRODUCTION,
    PERMISSION.VIEW_BENTO_WEEKLY_MENU,
    PERMISSION.EDIT_BENTO_WEEKLY_MENU,

    // Purchase
    PERMISSION.VIEW_PURCHASE,
    PERMISSION.EDIT_PURCHASE,
    PERMISSION.APPROVE_PURCHASE,
    PERMISSION.VIEW_PURCHASE_COSTS,
    // Manager does NOT have DELETE_PURCHASE or EXPORT_PURCHASE

    // Inventory
    PERMISSION.VIEW_INVENTORY,
    PERMISSION.EDIT_INVENTORY,

    // Reports
    PERMISSION.VIEW_REPORTS,

    // Dine-in
    PERMISSION.VIEW_DINE_IN,
    PERMISSION.EDIT_DINE_IN,

    // Reservations
    PERMISSION.VIEW_RESERVATIONS,
    PERMISSION.EDIT_RESERVATIONS,

    // Complaints
    PERMISSION.VIEW_COMPLAINTS,
    PERMISSION.EDIT_COMPLAINTS,

    // Incidents
    PERMISSION.VIEW_INCIDENTS,
    PERMISSION.EDIT_INCIDENTS,

    // Tasks
    PERMISSION.VIEW_TASKS,
    PERMISSION.EDIT_TASKS,

    // Staff
    PERMISSION.VIEW_STAFF_SCHEDULE,
    PERMISSION.EDIT_STAFF_SCHEDULE,
    // Manager does NOT have MANAGE_STAFF_ACCOUNTS or VIEW_ACTIVITY_LOG

    // Attendance
    PERMISSION.VIEW_ATTENDANCE_SELF,
    PERMISSION.VIEW_ATTENDANCE_ALL,
    PERMISSION.EDIT_ATTENDANCE_SELF,
    PERMISSION.EDIT_ATTENDANCE_ALL,

    // Checklist
    PERMISSION.VIEW_CHECKLIST_SELF,
    PERMISSION.VIEW_CHECKLIST_ALL,
    PERMISSION.EDIT_CHECKLIST_SELF,
    PERMISSION.VERIFY_CHECKLIST,
    PERMISSION.MANAGE_CHECKLIST_TEMPLATES,

    // Suppliers
    PERMISSION.VIEW_SUPPLIERS,
    PERMISSION.EDIT_SUPPLIERS,

    // Assets
    PERMISSION.VIEW_ASSETS,
    PERMISSION.EDIT_ASSETS,

    // Cashier
    PERMISSION.VIEW_CASHIER,
    PERMISSION.OPERATE_CASHIER,
    PERMISSION.CLOSE_CASHIER_SHIFT,

    // Profile
    PERMISSION.VIEW_PROFILE,
    PERMISSION.EDIT_PROFILE,

    // Sensitive
    PERMISSION.VIEW_CUSTOMER_PII,
    PERMISSION.VIEW_FINANCIAL_DATA,
    PERMISSION.VIEW_STAFF_PII,
  ],

  kitchen: [
    // Home (no revenue)
    PERMISSION.VIEW_HOME,
    PERMISSION.VIEW_HOME_ALERTS,

    // Bento — limited
    PERMISSION.VIEW_BENTO,
    PERMISSION.VIEW_BENTO_ORDERS,
    PERMISSION.VIEW_BENTO_PRODUCTION,
    PERMISSION.VIEW_BENTO_WEEKLY_MENU,
    // No EDIT_BENTO_ORDERS (uses set_bento_order_status RPC instead)
    // No VIEW_BENTO_CUSTOMERS, EDIT_BENTO_CUSTOMERS
    // No VIEW_BENTO_PAYMENTS, EDIT_BENTO_PAYMENTS

    // Purchase — record today's purchases (no costs, no supplier, no delete/export)
    PERMISSION.VIEW_PURCHASE,
    PERMISSION.EDIT_PURCHASE,
    // Kitchen does NOT have VIEW_PURCHASE_COSTS — prices/supplier never reach staff devices

    // Inventory
    PERMISSION.VIEW_INVENTORY,
    PERMISSION.EDIT_INVENTORY,

    // Tasks
    PERMISSION.VIEW_TASKS,
    PERMISSION.EDIT_TASKS,

    // Attendance — self only
    PERMISSION.VIEW_ATTENDANCE_SELF,
    PERMISSION.EDIT_ATTENDANCE_SELF,

    // Checklist — self only
    PERMISSION.VIEW_CHECKLIST_SELF,
    PERMISSION.EDIT_CHECKLIST_SELF,

    // Suppliers — removed: page exposes purchase cost totals (cost-hiding policy)

    // Assets — view only
    PERMISSION.VIEW_ASSETS,

    // Profile
    PERMISSION.VIEW_PROFILE,
    PERMISSION.EDIT_PROFILE,
  ],

  front_desk: [
    // Home (no revenue)
    PERMISSION.VIEW_HOME,
    PERMISSION.VIEW_HOME_ALERTS,

    // Bento — limited
    PERMISSION.VIEW_BENTO,
    PERMISSION.VIEW_BENTO_ORDERS,
    PERMISSION.EDIT_BENTO_ORDERS,
    PERMISSION.VIEW_BENTO_CUSTOMERS,
    PERMISSION.EDIT_BENTO_CUSTOMERS,
    PERMISSION.VIEW_BENTO_PAYMENTS,
    PERMISSION.EDIT_BENTO_PAYMENTS,
    PERMISSION.VIEW_BENTO_WEEKLY_MENU,
    // No VIEW_BENTO_PRODUCTION

    // Dine-in
    PERMISSION.VIEW_DINE_IN,
    PERMISSION.EDIT_DINE_IN,

    // Reservations
    PERMISSION.VIEW_RESERVATIONS,
    PERMISSION.EDIT_RESERVATIONS,

    // Complaints
    PERMISSION.VIEW_COMPLAINTS,
    PERMISSION.EDIT_COMPLAINTS,

    // Incidents
    PERMISSION.VIEW_INCIDENTS,
    PERMISSION.EDIT_INCIDENTS,

    // Tasks
    PERMISSION.VIEW_TASKS,
    PERMISSION.EDIT_TASKS,

    // Attendance — self only
    PERMISSION.VIEW_ATTENDANCE_SELF,
    PERMISSION.EDIT_ATTENDANCE_SELF,

    // Checklist — self only (front desk checklists like Cash Closing)
    PERMISSION.VIEW_CHECKLIST_SELF,
    PERMISSION.EDIT_CHECKLIST_SELF,

    // Assets — view only
    PERMISSION.VIEW_ASSETS,

    // Cashier
    PERMISSION.VIEW_CASHIER,
    PERMISSION.OPERATE_CASHIER,

    // Profile
    PERMISSION.VIEW_PROFILE,
    PERMISSION.EDIT_PROFILE,

    // Sensitive
    PERMISSION.VIEW_CUSTOMER_PII,
  ],

  // Future role — permissions defined but role not yet activated for any users
  delivery: [
    PERMISSION.VIEW_HOME,
    PERMISSION.VIEW_HOME_ALERTS,
    PERMISSION.VIEW_BENTO,
    PERMISSION.VIEW_BENTO_ORDERS,
    PERMISSION.VIEW_TASKS,
    PERMISSION.VIEW_ATTENDANCE_SELF,
    PERMISSION.EDIT_ATTENDANCE_SELF,
    PERMISSION.VIEW_PROFILE,
    PERMISSION.EDIT_PROFILE,
  ],
}
